### ISSUE TITLE
Npm update

### ISSUE THREAD

**Issue by luisfpinto** [bencevans/node-sonos#116]
Hello!
I'm installing node-sonos through npm but I think is outdate because is 0.9 version . Could you please confirm me that you have updated the repository? 

Thank you!

**Comment by bencevans** [comment]
Hi @luisfpinto 

I can confirm the npm repository is up to date. The version can be seen as 0.11.0 at https://www.npmjs.com/package/sonos

Maybe try pulling the set version: `$ npm install sonos@0.11.0`

:smiley_cat:
