### ISSUE TITLE
Topology Events Subscription Help needed

### ISSUE THREAD

**Issue by fwboettger** [bencevans/node-sonos#119]
Need some advice / support please with the Topology Event Subscription stuff:

I'm currently looking into the extending the homebridge-sonos plugin (https://github.com/nfarina/homebridge-sonos) to subscribe for sonos topology change events and to react accordingly to it (see also https://github.com/nfarina/homebridge-sonos/issues/4 in case of interest).

Based on the zoneTopologySubscription.js example, i've been looking at the event data being received upon such events, however the amount of data is massive and not everything is readily self explanatory. Any help (or even documentation to watch out for) regarding the event data details and how to interpret this would be highly appreciated.

Separately, i'd also highly appreciate any advice towards experiences and best practices related to "re-subscription / subscription renewal" (should one establish regular re-subscriptions, maybe on an hourly basis or similar, and if so how to best do it) as well as handling of broken subscriptions (e.g. client being shut down without properly removing an event subscription, anything to be taken into consideration hereto?). 

Thanks much in advance!

**Comment by bencevans** [comment]
I'm afraid I've not done a huge amount with the events. I'd suggest checking out the UPnP Specifications at http://www.upnp.org/specs/ 

They may be able to shed more light on how subscription renewel etc. should be handled.

Sorry I can't be of more help.

Kind regards

Ben
