### ISSUE TITLE
Playlists search only returns m3u

### ISSUE THREAD

**Issue by mnatte** [bencevans/node-sonos#123]
Somehow i cannot find the playlists i defined in my sonos system under Sonos playlists. The searchMusicLibrary only returns (imported) .m3u files. How can i get the Sonos playlists that i have defined in the Sonos app? Thanks!

**Comment by bencevans** [comment]
https://github.com/bencevans/node-sonos/pull/124 may well be what you're
looking for. Shall check and merge when I can.
