### ISSUE TITLE
getQueue ?

### ISSUE THREAD

**Issue by htilly** [bencevans/node-sonos#133]
Hi!

Quick question. What happened with the getQueue function?

BR
Tilly

**Comment by bencevans** [comment]
Hi @htilly 

I'm not sure that it's ever been implemented in this library...

```
$ git log --patch  | grep getQueue
$
```

The python library SoCo supports getting the queue https://github.com/SoCo/SoCo/pull/214/files
Any pull-request adding such functionality would be greatly appreciacted. At the moment you can get the current track with `sonos.currentTrack((err, track) => { ... })`.

**Comment by bencevans** [comment]
Added in bfb995610c8aa20bda09e370b0f5d31ba0caa6a0
