### ISSUE TITLE
Play favorite radio station

### ISSUE THREAD

**Issue by Rhaegar79** [bencevans/node-sonos#141]
Hello,

I got the URI of a favorite radio station with .getFavoritesRadioStations() and then tried to play it like this:

```
sonos.play('x-sonosapi-stream:s99172?sid=254&flags=32', function (err, playing) {
  console.log([err, playing])
})
```

The station won't play and I get this error:

> [ Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#AddURIToQueue"
>       at Request._callback (/home/pi/node_modules/sonos/lib/sonos.js:138:23)
>       at Request.self.callback (/home/pi/node_modules/request/request.js:198:22)
>       at emitTwo (events.js:106:13)
>       at Request.emit (events.js:191:7)
>       at Request.<anonymous> (/home/pi/node_modules/request/request.js:1035:10)
>       at emitOne (events.js:101:20)
>       at Request.emit (events.js:188:7)
>       at IncomingMessage.<anonymous> (/home/pi/node_modules/request/request.js:962:12)
>       at emitNone (events.js:91:20)
>       at IncomingMessage.emit (events.js:185:7),
>   undefined ]

What am I doing wrong?

Thanks for this great project!

Kind regards
Rhaegar

**Comment by Rhaegar79** [comment]
I should clarify: It's a TuneIn radio station.

When I use .queueNext() instead of play, the radio station is set as the current track. If I invoke a play afterwards, the radio station is played.
For URI I can't use the one I get with .getFavoritesRadioStations(). But, if I use the URI I get with getPositionInfo(), it works:
x-rincon-mp3radio://wdr-mp3-m-wdr2-muenster.akacast.akamaistream.net/7/349/119456/v1/gnl.akacast.akamaistream.net/wdr-mp3-m-wdr2-muenster

So, for me, it works. Is there anything I should do differently?

**Comment by pascal-fb-martin** [comment]
I had the same problem. I just found a work-around: extract the TuneIn station ID from the URI (:s<id>?) and call sonos.playTuneinRadio(id,'whatever').

Note that I do not use the title from the favorite. This is because node-sonos does not handle properly HTTP special characters, such as '&' (as in "R&B").

**Comment by svrooij** [comment]
The `x-sonosapi-stream:s....` requires metadata this is way this doesn't really work. You can use the `sonos.playTuneinRadio(id, 'whatever', callback)` or use `sonos.playWithoutQueue('radio:id', callback)`
You can also check-out the [PlayTuneIn sample](https://github.com/bencevans/node-sonos/blob/master/examples/playTuneinRadio.js)

Closing this for now, you can reopen this issue if needed.
