### ISSUE TITLE
500 Errors with several Endpoints

### ISSUE THREAD

**Issue by kswilster** [bencevans/node-sonos#142]
Using `Sonos#play`, `Sonos#next` and other methods I get the following errors.

ERROR: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Play"
ERROR: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Next"

I have encountered these through use of the [sonos-cli](https://github.com/bencevans/sonos-cli) project as well as using this API directly.

**Comment by Pierre-Gilles** [comment]
I have these errors as well when trying to play music using spotify : 

`[Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#AddURIToQueue"]`  

Here is my code, it's basically the example : 

```javascript
var Sonos = require('sonos').Sonos
var sonos = new Sonos('MY_SONOS_IP');

var spotify_track_id = '4XTTwW06rMgud7yS1nySZf' // Slayer ftw

sonos.addSpotify(spotify_track_id, function (err, res) {
  console.log(err)
  console.log(res)
});
```

**Comment by nitriques** [comment]
I have a similar error using the cli

```
...\npm\node_modules\sonos-cli\cmds\play.js:14
          throw err
          ^

Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#SetAVTransportURI"
```

**Comment by bencevans** [comment]
I'm unable to reproduce. Is anyone able to provide more information as to what you were trying to play and/or what was playing before. I.e. radio/spotify/local library

@kswilster @nitriques your issues may be the same here however this is working for me...

```
➜  node-sonos git:(master) sonos list-devices
Portable
  group:  RINCON_000E585B7C9801400:3
  coordinator:  true
  wirelessmode:  1
  wirelessleafonly:  0
  hasconfiguredssid:  1
  channelfreq:  2437
  behindwifiext:  0
  wifienabled:  1
  location:  http://192.168.0.20:1400/xml/device_description.xml
  version:  33.15-33210
  mincompatibleversion:  32.0-00000
  legacycompatibleversion:  25.0-00000
  bootseq:  60
  uuid:  RINCON_000E585B7C9801400
  name:  Portable

➜  node-sonos git:(master) sonos --zone RINCON_000E585B7C9801400:3 play
Playing...
```

@Pierre-Gilles #118 may be more in line with the issue you're seeing.

**Comment by htilly** [comment]
Hi guys.

Don´t know if this is related, but we´re having the same problem with our Sonos.
If we use:
sonos.addSpotify
we´re receiving an 500 error...

But if we uses sonos.addSpotifyQueue, everything works fine...

BR Tilly

**Comment by jangrewe** [comment]
Hi all, i can confirm what @htilly says, i have to use addSpotifyQueue() to make it work.

**Comment by nitriques** [comment]
@bencevans I still get the error, even after usign sonos.addSpotifyQueue.

I am running the cli, which uses an old version of the lib.

```
 sonos     ^0.11.1  →  ^0.12.1
 standard   ^6.0.7  →   ^8.6.0
```

I tried to update, but it's now crashing the sonos itself...

**Comment by jthawme** [comment]
I was having this issue too, and it seems to be at least for my case that its because the queue was not in use.

If I had something already playing then used for instance the '.play()' command, it would work correctly.

Is there any command to put the queue in use from the API?

**Comment by jthawme** [comment]
Apologies, just seen in the code there is in fact a selectQueue function, it just isnt in the API readme

**Comment by laurensV** [comment]
calling selectQueue() before doing queue or queueNext or addSpotify does not fix the issue for me :(

**Comment by albinekb** [comment]
same here @laurensV

**Comment by ds82** [comment]
I'm having the same issue. If I compare the UPNP message that the sonos app and this node module sends to play a spotify playlist, they are quite different.

This module:
```
...
<EnqueuedURI>x-sonos-spotify:spotify%3atrack%3aspotify:user:XXX:playlist:YYY</EnqueuedURI>
...
```

sonos App:
```
<EnqueuedURI>x-rincon-cpcontainer:1111111cspotify%3auser%3aspotify%3aplaylist%YYY</EnqueuedURI>
```

Does this may give any hint why its not working for some users?

**Comment by ds82** [comment]
Further digging showed, that node-sonos indeed sends ``x-rincon-cpcontainer`` messages, too (I honestly don't know what I did to produce the ``x-sonos-spotify`` message posted above). Anyway, I looked further and found the solution for my specific problem.

Another differences between the sonos app and this module are the meta data. The message this module sends contains the string ``SA_RINCON3079_X_#Svc3079-0-Token``, the official app uses ``SA_RINCON2311_X_#Svc2311-0-Token`` (I have no idea what that means, I just diffed the XML messages).

Changing ``lib/sonos.js`` line 77 from

```
  var meta = '<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="##SPOTIFYURI##" restricted="true"><dc:title>##RESOURCETITLE##</dc:title><upnp:class>##SPOTIFYTYPE##</upnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">SA_RINCON3079_X_#Svc3079-0-Token</desc></item></DIDL-Lite>'
```
to

```
  var meta = '<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="##SPOTIFYURI##" restricted="true"><dc:title>##RESOURCETITLE##</dc:title><upnp:class>##SPOTIFYTYPE##</upnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">SA_RINCON2311_X_#Svc2311-0-Token</desc></item></DIDL-Lite>'
```

fixed it for me.

**Comment by ds82** [comment]
It seems, that ``SA_RINCON2311_X_#Svc2311-0-Token`` is the service ID for spotify EU. I assume, that ``SA_RINCON3079_X_#Svc3079-0-Token`` is spotify US. 

@everone who reported the bug before me - let me guess - you all are using spotify EU?

**Comment by htilly** [comment]
@ds82 yes, can confirm EU!

**Comment by albinekb** [comment]
Awesome!! Thanks

**Comment by ds82** [comment]
@nitriques Can you use tcpdump to record a play tcp message from the official sonos app that works for you?

**Comment by nitriques** [comment]
Would it work if I use a dev proxy ? Is it all http ? Or could I use wireshark ?
