### ISSUE TITLE
PLAYBAR | Switching between TV Audio and Music

### ISSUE THREAD

**Issue by amitgandhinz** [bencevans/node-sonos#148]
Has anyone looked into the ability to programmatically switch the Audio streams on the Playbar?

When using functions such as `play` and `stop`, they will only work when the Playbar is in Music mode.  While in TV mode with the audio in line, it will return a 500.

Basically I want to be able to call `play()` and have the sonos switch to audio mode and start playing the queue/playlist.  When I stop, i would like it to switch back to the TV audio input.

This issue may be related to #142 but not sure as they have not indicated what sonos device they are using.

**Comment by bencevans** [comment]
Aaah yes, this may well be the background to #142!

Support for switching manually too would also be great.

**Comment by amitgandhinz** [comment]
im going to see what i can find out here.

just noting helpful hints here as i investigate how to switch the input 
- https://github.com/SoCo/SoCo/blob/master/soco/core.py#L980

**Comment by ebaauw** [comment]
When the Playbar is in TV mode it doesn't accept Play nor Pause, Next, ..., hence the 500 error code.  The Sonos app disables these controls when in TV mode.

When in TV mode, the Playbar plays a stream of type `x-sonos-htastream`.  This is different from the audio in of a Play:5 or Connect, which are of type `x-rincon-stream`.  As far as I can tell, the only way to get the Playbar out of TV mode is to select a different music source through the `SetAVTransportURI` action in the `AVTransport` service.

By selecting `TV Autoplay` in `TV Setup` under the Room Settings of the Sonos app, the Playbar switches automatically to TV mode, when it detects input on the optical audio interface.  No need to switch back to TV mode on Stop.  This setting can be accessed through the Playbar's `HTControl` service.

**Comment by svrooij** [comment]
The latest version (on git currently) has direct access to the `SetAVTransportURI` through `sonos.playWithoutQueue(uri)` so that can be used to switch to TV/line-in mode as shown [in this sample](https://github.com/svrooij/node-sonos/blob/master/examples/switchToLineIn.js).

I think getting out of the TV mode, requires you to select the queue with `sonos.selectQueue` or by starting a TuneIn/Spotify radio station.

**Comment by MikaAK** [comment]
Is there a solution to this? I tried the code from the example and was still hit with 500 errors

**Comment by svrooij** [comment]
Could you create a new issue for your problem. We set-up an issue template that helps us solving issues faster.

Without the output of some example it is really hard to diagnose the problem.

**Comment by MikaAK** [comment]
For sure! I just didn't want to create a new issue for an old one before asking 😄
