### ISSUE TITLE
Typescript definitions?

### ISSUE THREAD

**Issue by jabooth** [bencevans/node-sonos#149]
I'm a little confused, on the `CHANGELOG.md` it's mentioned under [Unreleased] that
> TypeScript definitions (thanks to SPARTAN563)

But I can't see find the relevant types/PR on DefinitelyTyped or on this repo...am I missing something?

I might be able to contribute the types if they haven't already been done, but obviously don't want to duplicate work!

**Comment by bencevans** [comment]
Oh damn, that was for a different project (node-influx). Doh! Happy to add TypeScript definitions if you're up for maintaining?

**Comment by svrooij** [comment]
@jabooth Don’t know if this is still relevant but https://github.com/svrooij/node-sonos-ts
