### ISSUE TITLE
Search() crashes when called with a timeout.

### ISSUE THREAD

**Issue by ebaauw** [bencevans/node-sonos#150]
I recently upgraded from node-sonos@0.8.0 to node-sonos@0.12.1.

When I call the `Search()` function with a `timeout` specified in the `options`, node-sones crashes with the following error:

> dgram.js:530
>    throw new Error('Not running'); // error message from dgram_legacy.js
>   ^
>
>Error: Not running
>    at Socket._healthCheck (dgram.js:530:11)
>   at Socket.send (dgram.js:350:8)
>    at /Users/ebaauw/GitHub/homebridge-zp/node_modules/sonos/lib/sonos.js:1047:19
>    at Array.map (native)
>    at Timeout.sendDiscover [as _onTimeout] (/Users/ebaauw/GitHub/homebridge-zp/node_modules/sonos/lib/sonos.js:1046:44)
>    at ontimeout (timers.js:365:14)
>    at tryOnTimeout (timers.js:237:5)
>   at Timer.listOnTimeout (timers.js:207:5)

As far as I can tell, `self.socket` has been closed by the timeout (line 1073), causing this error.  I think the timeout needs to cancel `self.pollTimer` before closing `self.socket`.

**Comment by Easen** [comment]
Opened a pull request #151 to resolve this issue, I take no credit for this @ebaauw did all of the hard work tracking it down!

**Comment by bencevans** [comment]
Fix released in [`v0.13.0`](https://github.com/bencevans/node-sonos/commit/46179a8292d0c2499eee0b0795be9774103bd5c7).
