### ISSUE TITLE
Possible EventEmitter Leak in code

### ISSUE THREAD

**Issue by gupsho** [bencevans/node-sonos#157]
Hi,

I am using the library to search for sonos devices on my network. And I never destroy the search object. After a couple minutes of my process running I see this error

Possible EventEmitter memory leak detected. 11 timeout listeners added. Use emitter.setMaxListeners() to increase limit

I see that at /lib/sonos.js:1082, the onTimeout listener gets aadded again and again and is not removed. 

I am very new to nodejs and I am not sure if this is the right fix but I was able to fix it by changing the code slightly from:

self.on('timeout', function () {
      clearTimeout(self.pollTimer)
 })

to

this.onTimeout = function onTimeout() {
      clearTimeout(self.pollTimer)
}    

self.removeListener('timeout', onTimeout);                                                                                                                                                                                                
self.on('timeout', onTimeout)

Would you please advise on the right fix for this?

**Comment by gupsho** [comment]
I tried fixing it in https://github.com/bencevans/node-sonos/pull/159

**Comment by bencevans** [comment]
Thanks!
