### ISSUE TITLE
Question: Sonos.js vs Services classes

### ISSUE THREAD

**Issue by toddanglin** [bencevans/node-sonos#165]
Hey Ben-

First, great project! Thanks for sharing and helping make it easier control Sonos systems from Node/JavaScript. Mucho appreciated.

I'm trying to adapt this library to work in NativeScript mobile projects, and I have a question about the `Sonos.js` class versus all of the classes in `Services` (as there is some overlap).

**Was the intent with the `Service` classes to refactor the code towards a more modular architecture and move away from the monolithic `Sonos` class? Or are they just an old artifact in the project?**

Obviously, most of the implementation today seems to be in `Sonos.js` (and most of the demos uses this class). But it appears the `Services` classes cover more of the Sonos API and improve upon the code organization a bit. Just curious before I spend time fleshing-out the `Service`-based approach.

Thanks!

**Comment by bencevans** [comment]
Hi Todd,

I originally generated the service files with the thought that they'd be used more in place of the monolith. To use them effectively I think we'd need a generic Service which they extend providing helpers (request/response parsing, connection management etc.). It would be great to move to in the future however I don't see myself working on this any time soon. Pull-requests are gratefully received though and always on the lookout for people to join and maybe lead the development of this project moving forward.

Cheers,

Ben
