### ISSUE TITLE
tunein radio

### ISSUE THREAD

**Issue by simondid** [bencevans/node-sonos#166]
hey

so i'm working on a java based sonos controller and was hoping you might be able to help me 

i'm having truble adding / playing radio stations from tunein and i was hoping you cut post the raw calles you make to the sonos device when adding / playing a radio station

**Comment by bencevans** [comment]
Hi

The code we use you can find at https://github.com/bencevans/node-sonos/blob/e27de740fa7415f2616fc440283383cab2ddabbe/lib/sonos.js#L577-L603

If you're wanting to inspect the raw packets I'd suggest getting yourself [Wireshark](https://www.wireshark.org/) and using the Official Sonos Client you can inspect the packets sent/received.

**Comment by simondid** [comment]
that is what i'm doing but it seems to give some wired result like adding 2 diffrent trakcs/streams to the queue ore start playing the radio station but this dos contain a usefull name ore track/stream picture
