### ISSUE TITLE
Can we expose the Listener module? 

### ISSUE THREAD

**Issue by gupsho** [bencevans/node-sonos#167]
I would like to get callbacks whenever state for Sonos changes rather than polling. Is it possible to expose the listener module?

For now I made changes locally in my fork here: 
https://github.com/gupsho/node-sonos/commit/c8fda261637e10899a4558ed84494957a21ab49b

Is it possible to support it in here?

**Comment by mrose17** [comment]
please submit a pull request!

**Comment by bencevans** [comment]
PR @ #168. Waiting for #196 review + merge to fix Travis test before merging #168.
