### ISSUE TITLE
Short announcement and continue playing

### ISSUE THREAD

**Issue by svrooij** [bencevans/node-sonos#170]
I was wondering how to implement the following:

1. Sonos is either playing or paused
2. I play an MP3 (either a gong sound or an announcement e.g. Google TTS)
3. Sonos should continue the previous state (restore playlist and same state at 1.)

Is there an method for this? Or should I query the playlist & status then play MP3 and then manually restore the playlist and state?

**Comment by bencevans** [comment]
You will need to restore some sort of state. That may be the current track that's playing and progress through or the type of input (line-in/stream/queue).

I'm going to close this as an issue. Would love to hear if you work out a method. Please feel free to use this to discuss if anyone else joins!
