### ISSUE TITLE
 Refusing to install sonos as a dependency of itself

### ISSUE THREAD

**Issue by FlavioKt** [bencevans/node-sonos#173]
Hi,
I'm trying to install node-sonos, but the command "npm install sonos" ends with the message
"Refusing to install sonos as a dependency of itself".

[npm-debug.txt](https://github.com/bencevans/node-sonos/files/1034255/npm-debug.txt)

Could you help me?

Thanks in advance

Flavio

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'sonos' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData sonos
8 silly fetchNamedPackageData sonos
9 silly mapToRegistry name sonos
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'sonos',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'sonos',
12 silly mapToRegistry   name: 'sonos',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/sonos
14 verbose request uri https://registry.npmjs.org/sonos
15 verbose request no auth needed
16 info attempt registry request try #1 at 16:34:56
17 verbose request id 304962b18d04a107
18 verbose etag W/"58750a68-9149"
19 verbose lastModified Tue, 10 Jan 2017 16:23:04 GMT
20 http request GET https://registry.npmjs.org/sonos
21 http 304 https://registry.npmjs.org/sonos
22 verbose headers { date: 'Sun, 28 May 2017 14:35:05 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"58750a68-9149"',
22 verbose headers   age: '36',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-hhn1536-HHN',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1495982106.633858,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Sun, 28 May 2017 14:35:05 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"58750a68-9149"',
23 silly get     age: '36',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-hhn1536-HHN',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1495982106.633858,VS0,VE0',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/sonos from cache
25 verbose get saving sonos to C:\Users\Flavio\AppData\Roaming\npm-cache\registry.npmjs.org\sonos\.cache.json
26 verbose correctMkdir C:\Users\Flavio\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install sonos as a dependency of itself
43 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
43 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
43 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
44 verbose cwd E:\Sonos\node-sonos-master
45 error Windows_NT 10.0.14393
46 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sonos"
47 error node v6.10.3
48 error npm  v3.10.10
49 error code ENOSELF
50 error Refusing to install sonos as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by bencevans** [comment]
When in this repository you should just run `npm install` to download the dependencies.

**Comment by FlavioKt** [comment]
Hi, 

thanks for the very prompt response.

Another question: I tried to run using "npm start", as for other packages, but I got the answer:


"E:\Sonos\node-sonos-master>npm start
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Sonos\node-sonos-master\npm-debug.log

Could You help me again?

Thank you very much.

Flavio

**Comment by bencevans** [comment]
@FlavioKt this is a library rather then any sort of application. You can install the module in your own project using `npm install --save sonos` then require it at the top of your own application with `var sonos = require('sonos')` and call methods described in the README/API.md files.

**Comment by FlavioKt** [comment]
Thank you very much for the answer

Flavio


Il 04/06/2017 19:47, вєη єναηѕ ha scritto:
