### ISSUE TITLE
npm Version does not match git Features

### ISSUE THREAD

**Issue by MexXxo** [bencevans/node-sonos#174]
The current npm version, does not match the API / Features that are described in the Git Master.
I ran into the issue, that I was trying to use the setSpotifyRegion (btw. example and API.md are telling two function names: setSpotifyRegion and setRegion) and figured out that it is not part of the current npm Version (0.14.1). 
I would suggest to use a branch for the current develop as otherwise people are reading an API and Examples that might not exist using npm install. 

If only finished features are getting into the master branch, than a simple version bump would be enough :)

**Comment by bencevans** [comment]
Hi @MexXxo, the version on npm has now been bumped to `v0.15.0` https://github.com/bencevans/node-sonos/commit/afadd1ae80ae22274a4cd33579ccc9dc109bb6ee

Thanks for raising this, if you have any suggestions as to how best to make this obvious to future users please do share.

**Comment by bencevans** [comment]
Hi @MexXxo, the version on npm has now been bumped to `v0.15.0` https://github.com/bencevans/node-sonos/commit/afadd1ae80ae22274a4cd33579ccc9dc109bb6ee

Thanks for raising this, if you have any suggestions as to how best to make this obvious to future users please do share.
