### ISSUE TITLE
Sonos library doesnt return an error when a non-premium spotify account is used to play a track

### ISSUE THREAD

**Issue by gupsho** [bencevans/node-sonos#175]
The library returns success when a non premium spotify account is used to play a song even though the actual playback fails.  I am using the play api, passing in the spotify track url.

**Comment by gupsho** [comment]
I do see an event emitted which says account is unsupported.
{"LastChange":"<Event xmlns=\"urn:schemas-upnp-org:metadata-1-0/AVT/\" xmlns:r=\"urn:schemas-rinconnetworks-com:metadata-1-0/\"><InstanceID val=\"0\"><TransportStatus val=\"**ERROR_SONOS_UNSUPP_ACCOUNT**\"/><TransportErrorDescription val=\"55,3079,Ho Hey,Spotify,x-sonos-spotify:spotify%3atrack%3a0W4Kpfp1w2xkY3PrV714B7?sid=12&amp;flags=8224&amp;sn=5,\"/><TransportErrorURI val=\"x-sonos-spotify:spotify%3atrack%3a0W4Kpfp1w2xkY3PrV714B7?sid=12&amp;flags=8224&amp;    sn=5\"/></InstanceID></Event>"}

I am guessing there is no way to return this information in the callback passed to play?

**Comment by bencevans** [comment]
An error could be passed back to the callback with an error explaining the issue.

**Comment by gupsho** [comment]
But the callback is sent as soon as the call to play(which just adds the song to queue) succeeds. I think the failure happens when sonos try to actually play it.

**Comment by bencevans** [comment]
How did you gather the error you shared above? You mention you see an event emitted. Is this to a Sonos Controller, seen through Wireshark or a response to a request made by node-sonos?

**Comment by gupsho** [comment]
I had an eventListener for 'serviceEvent' emitted from the code. Thats where I saw the message.

**Comment by svrooij** [comment]
With wireshark I discovered a new endpoint that will display the spotify account status, that could be used to verify a premium account before playback.

The endpoint is `http://192.x.x.x:1400/spotifyzc?action=getInfo` and in my case (premium account) it returns the following.

```json
{
  "status": 101,
  "statusString": "ERROR-OK",
  "spotifyError": 0,
  "version": "2.3.0",
  "deviceID": "RINCON_***:10",
  "publicKey": "Obviously_not_my_account_key",
  "modelDisplayName": "PLAY:1",
  "activeUser": "my_spotify_username",
  "accountReq": "PREMIUM",
  "deviceType": "SPEAKER",
  "libraryVersion": "2.56.45-g39a635a0",
  "resolverVersion": "1",
  "tokenType": "authorization_code",
  "clientID": "you_re_kidding_right_wink",
  "scope": "streaming",
  "brandDisplayName": "Sonos",
  "remoteName": "name_of_the_speaker"
}
```


@gupsho could you output your info (without premium), maybe we could build something like:

```node
sonos.checkSpotifyPremium((got_premium) => { 
  if (got_premium) console.log('We got premium spotify')
})
```

**Comment by svrooij** [comment]
If the above would be possible would that fix your issues?
Like

```node
sonos.checkSpotifyPremium((got_premium) => { 
  if (got_premium) console.log('We got premium spotify')
})
```

Because that is an easy fix, which I will implement soon. If that doesn’t fix your issue could you please re-open it?

**Comment by gupsho** [comment]
I am getting a 403 for my sonos for that url. Also I think the response that you are getting might just be saying that accountRequired is premium and not that premium account is actually connected.

**Comment by svrooij** [comment]
If you're getting a 403 with that URL that just might be the trick. Because I have a Spotify account connected, so going to use this URL for now and create a function for you to check if there is a premium account.

**Comment by svrooij** [comment]
With the new version (in the sonos-async branch) you can request the spotify info (as above). And you can subscribe to the `AVTransport` event on the sonos speaker if you want the above error.

Their can't be an error on the `Play()` command, because it will return when a succesfull call the play this uri endpoint is called.

If you think this doesn't fix your problem please re-open it.
