### ISSUE TITLE
Spotify Error 500 - AVTransport:1#Seek

### ISSUE THREAD

**Issue by CTKRocks** [bencevans/node-sonos#176]
Here's the code:
```javascript
  Sonos.search(function (device, model) {
  var devInfo = '\n'
  devInfo += 'Device \t' + JSON.stringify(device) + ' (' + model + ')\n'
  device.getZoneInfo(function (err, info) {
    if (err) devInfo += '`- failed to retrieve zone information\n'

    devInfo += '`- info: \t' + JSON.stringify(info).replace(/",/g, '",\n\t\t') + '\n'

    console.log(info["IPAddress"]);
    sonos = new Sonos.Sonos(info["IPAddress"]);
    var spotifyUri = "spotify:track:33kAXkQiwseu6RVSXRiF0Y";
    console.log(spotifyUri);
    sonos.play(spotifyUri, (err, result) => {
      if (err) {
        return console.log(err)
      }
    });
  })
})
```

I get: `[Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Seek"]`

**Comment by gupsho** [comment]
If the sonos does not have any active queue at this time or if its the first time you trying to play after sonos boots up, you need to selectQueue before playing.

Get device state by calling getCurrentState
`device.getCurrentState((err, playerState) => {
});`

then do this.

`if (!playerState || playerState === 'stopped') {
    sonos.selectQueue((err, result) => {
        if (!err) {
            sonos.play(spotifyUri, (err, result) => {
           });
        }
    });
 }`

Hope this helps.

**Comment by CTKRocks** [comment]
Thanks! I'll try this later.

**Comment by CTKRocks** [comment]
Got it working! Thanks!
