### ISSUE TITLE
Previous/Next song at the start/end of queue

### ISSUE THREAD

**Issue by msunjic98** [bencevans/node-sonos#180]
Apparently, when you try to trigger device.previous() or device.next() when at the first or last song of the queue, the library crashes.

`Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Next"
    at Request._callback (/home/unm4sk/Desktop/homeserver-dev/node_modules/sonos/lib/sonos.js:153:23)
    at Request.self.callback (/home/unm4sk/Desktop/homeserver-dev/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/unm4sk/Desktop/homeserver-dev/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/unm4sk/Desktop/homeserver-dev/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
`

Any fix for this or should I check the queue manually?

**Comment by bencevans** [comment]
It would be interesting to see what's actually in the response. Maybe there's an error identifier we can use to throw a more useful error.

**Comment by msunjic98** [comment]
Didn't get anything else other than this, workaround would be to check the queue position and block it if it's first/last song, but I guess we could do something initially in the library. Will look into it.

**Comment by svrooij** [comment]
You can only next with replay mode turned on when you're on the last song of the list.

Just checked the example and it doesn't crash (on my computer), it just response with the same in both ways.

Not in replay mode, when on last song (nothing happend):
```bash
MBP:node-sonos stephan$ SONOS_HOST=192.168.96.56 DEBUG=sonos node examples/next.js 
  sonos Sonos.next(undefined) +0ms
  sonos Sonos.request("/MediaRenderer/AVTransport/Control", "\"urn:schemas-upnp-org:service:AVTransport:1#Next\"", "<u:Next xmlns:u=\"urn:schemas-upnp-org:service:AVTransport:1\"><InstanceID>0</InstanceID><Speed>1</Speed></u:Next>", "u:NextResponse", undefined) +2ms
Complete
```

In replay mode (went to next song):
```bash
MBP:node-sonos stephan$ SONOS_HOST=192.168.96.56 DEBUG=sonos node examples/next.js 
  sonos Sonos.next(undefined) +0ms
  sonos Sonos.request("/MediaRenderer/AVTransport/Control", "\"urn:schemas-upnp-org:service:AVTransport:1#Next\"", "<u:Next xmlns:u=\"urn:schemas-upnp-org:service:AVTransport:1\"><InstanceID>0</InstanceID><Speed>1</Speed></u:Next>", "u:NextResponse", undefined) +2ms
Complete
```

**Comment by svrooij** [comment]
@msunjic98 could you check if the library still crashes? Or could you supply us with test code that actually crashes?

Closing this issue for now, because it doesn’t crash at my computer and we need some more info to check this out. Feel free to re-open this issue if you still think it is crashing
