### ISSUE TITLE
Unset playmode

### ISSUE THREAD

**Issue by gupsho** [bencevans/node-sonos#183]
How do I unset a playMode once set?

So if I call 
setPlayMode('repeat', callback);
setPlayMode('shuffle', callback);

now how do I unset shuffle if I want to?

**Comment by bencevans** [comment]
Give `.setPlayMode('normal', cb)` a whirl.

Options appear to be:

* `'normal'`
* `'repeat_all'`
* `'shuffle'`
* `'shuffle_norepeat'`

Underlying code:

https://github.com/bencevans/node-sonos/blob/e069868b40fa8274da8069f38b9752ba36c115df/lib/sonos.js#L889-L904

**Comment by gupsho** [comment]
But normal will remove both shuffle and repeat? Does setting a playMode replace previous playMode?
So if I say repeat after shuffle does repeat automatically go away? Also is there a way to getPlayMode?

**Comment by bencevans** [comment]
That would make the most sense to me. Fancy testing #184 out? :smile_cat:

**Comment by gupsho** [comment]
Will do. Thanks for the quick update.
