### ISSUE TITLE
Support for adding Spotify playlists ?

### ISSUE THREAD

**Issue by htilly** [bencevans/node-sonos#186]
Hi!

Is there any way to add Spotify playlists ?
sonos.addSpotify(spid, function (err, res) works great for adding tracks..  but how to add playlists to the queue?

BR
Tilly

**Comment by gupsho** [comment]
I think using play with a playlist uri would achieve the desired behavior. So instead of using addSpotify, use play for playlist.

**Comment by bencevans** [comment]
If someone puts this to the test please report back :smiley_cat:

**Comment by MexXxo** [comment]
I tried with sonos@0.18.0 and I could not get my sonos play out any spotify uri (tried playlist, album, artist) using the play function.
I'm using Spotify Europe and also the playSpotifyRadio did'nt worked for me.
Can someone confirm that spotify EU is working with node-sonos?

**Comment by bencevans** [comment]
@MexXxo did you try using the `.addSpotify()` function?
