### ISSUE TITLE
playTuneinRadio does not handle special http characters in the station title

### ISSUE THREAD

**Issue by pascal-fb-martin** [bencevans/node-sonos#190]
I query the list of favorite stations (getFavoriteRadioStations) and use the result to select one station to play using playRadioStation. The station title comes from the data returned by getFavoriteRadioStations.

The station does not play (HTTP error 500) if the title contains a character '&' (as in "R&B"). If I replace the character '&' with something else (like a space), it works. If I replace the title with some arbitrary string constant, it works.

**Comment by bencevans** [comment]
I imagine it's to do with the [`htmlEntities`](https://github.com/bencevans/node-sonos/blob/8b64efa141970480673b2cd0e76d6551bc179b48/lib/sonos.js#L59-L66) [call](https://github.com/bencevans/node-sonos/blob/8b64efa141970480673b2cd0e76d6551bc179b48/lib/sonos.js#L665). A pull-request would be much appreciated if a solution found.

**Comment by svrooij** [comment]
@pascal-fb-martin is the title even used? Seen this in the Spotify api as well, but I don't get it to show up in the official sonos application.

So maybe it's better to just not set the title and just set it to `RadioStation`.

**Comment by pascal-fb-martin** [comment]
In fact I first tested with a similar constant string. Then I decided to use a "sanitized" variant of the station name, just in case the Sonos app uses that string in its user interface (why would they have such a parameter otherwise?). Ideally, I would not need to set that name and just let Sonos uses its own name, if that is possible.

So I would be fine with making the parameter optional in the API. That would also convey that it does not need to match the name provided by the Sonos. "RadioStation" seems like a good default if the Sonos web API requires that parameter; however if that name is also optional in the Sonos web API, then it would make sense to not set it there either in this case.

**Comment by svrooij** [comment]
I never found where they show it. Maybe it is used before the metadata of the station is fetched from the server. Anyway as of #200 you can also start radio by doing the following (and that doesn't need a Station name, set to `TuneIn Radio`)

```node
sonos.playWithoutQueue('radio:' + stationId, (err, playing) => { console.log('Woot')});
```

I'm closing this issue for now feel free to open it again if this doesn't solve your problem.
