### ISSUE TITLE
Enhance listener functionality

### ISSUE THREAD

**Issue by ebaauw** [bencevans/node-sonos#205]
Allow subscribing to any service.

For my homebridge-zp plugin, I'm currently subscribing to events from `GroupManagement`, `MediaRenderer/AVTransport`, `MediaRenderer/GroupRenderingControl`, `MediaRenderer/RenderingControl` and `AlarmClock` services.  `ZoneGroupTopology` events are on my backlog, but with the current design of homebridge-zp cannot dynamically add or remove HomeKit accessories, so I cannot do anything with these at the moment.

The way I've implemented it in homebridge-zp, I create a single instance of (the equivalent of) Listener and subsequently do a subscribe per service per zone player.  The listener parses the event, figures out which zone player and service it came from and then issues (the equivalent of) an `player.emit(serviceName)`, where `player` would be an instance of `sonos`.

**Comment by svrooij** [comment]
Some guy made some nice changes to the event system [here](https://github.com/thkl/node-sonos/tree/master/lib/events).
So that could maybe also be implemented in this repo.

**Comment by svrooij** [comment]
Have a look at my sample for listening for events https://github.com/bencevans/node-sonos/blob/sonos-async/examples/events.js

It will implement a new SINGLE listener for global events (still wip) but you should see how it works in the [new listener](https://github.com/bencevans/node-sonos/blob/sonos-async/lib/events/adv-listener.js)

**Comment by svrooij** [comment]
@ebaauw what do you think about my work on the listener part? Can this issue be closed?

**Comment by svrooij** [comment]
In the current version in the sonos-async branch I created a new listener that is shared between all instances. This made it much easier to develop listener functionality. While there is still some room for improvements, I think we can close this issue for now.

If you find to have some issues with the new listener, please open a new issue.
