### ISSUE TITLE
Easy task: Converting four tests to async

### ISSUE THREAD

**Issue by svrooij** [bencevans/node-sonos#217]
At the moment most tests are converted to async with `nock`, but some are still commented out. And we would like those to be restored and converted to async.

———————

The current mocha test work by replacing the `request` function on a `Sonos` instance. This will no longer work when everything is converted to `Promises`.

Anyone got an idea on how to still run tests on the async library? Was thinking about a fake sonos device (just a http server) that responds to some urls and that will check the test cases.

**Comment by bencevans** [comment]
[nock](https://github.com/node-nock/nock) creates an interceptor on `http.request` to stub requests/mock responses without actually hitting the network. Expected responses can then be kept with each test for easy referencing when fixing issues

**Comment by svrooij** [comment]
Could you create a sample on the async branch? Then maybe other people can help out moving the tests to the async version.

**Comment by svrooij** [comment]
In [this commit](https://github.com/bencevans/node-sonos/commit/dbf8a95e009f419936fd88c48a63871929f8679f) I fixed a few test cases. The rest is commented. Could someone else fix the rest and send a pull request.

**Comment by iansu** [comment]
I'm working on this now. I should have a PR to submit soon.

**Comment by svrooij** [comment]
Thanks @iansu
