### ISSUE TITLE
Call for testers

### ISSUE THREAD

**Issue by svrooij** [bencevans/node-sonos#218]
I’ve done a lot of work on converting everything to async in a new [sonos-async branch](https://github.com/bencevans/node-sonos/tree/sonos-async) now is the time for everyone to start testing this new version.

Please check it out and let us know what you think!

**Comment by svrooij** [comment]
If you want to use the new version of node-sonos in your project you can refer to it in your `package.json` like:
```JSON
"dependencies": {
  "request": "^2.83.0",
  "semver": "^5.4.1",
  "sonos": "bencevans/node-sonos#sonos-async",
  "xml2js": "^0.4.19"
},
```

Let us know, what you think.

**Comment by svrooij** [comment]
Hello users of this library, could you please let us know what you think of the async version. Is it stable enough for a release?

- [ ] @ebaauw 
- [ ] @iansu
- [ ] @bencevans 
- [ ] @vinkla 
- [ ] @gupsho 
- [ ] @sammygriffiths 
- [ ] @htilly

**Comment by vinkla** [comment]
Hey, thanks for making it async! I've just tried the new version briefly and it works. 

Also, great work on the updated documentation!

**Comment by bencevans** [comment]
'async' is a bit confusing given it's always been asynchronous. In future esp. with changelogs etc. I propose we call it promises. I'm unable to actually test functionality as I don't have access to Sonos devices for another month or so but if others can test and give the thumbs up I'd love to see this get pushed through as 1.x 😺
