### ISSUE TITLE
Play uri (notification) and restore state

### ISSUE THREAD

**Issue by svrooij** [bencevans/node-sonos#221]
With all the async stuff done, the following would finally be possible.
One function to play a single uri (mp3 file, TTS file) and afterwards restore the original state.

1. Fetch current state
2. Fetch the current playing uri (queue or TuneIn radio)
3. Play the uri
4. Subscribe to `State` event
5. When the state changes to ???, restore the previous stored values.

This function could then be used to play a `DINGDONG` when someone is at the door. Or be used together with some text-to-speech engine.

Would also like to see the following optional options implemented:

- onlyWhenPlaying
- setVolumeTo

What do you guys think? Anyone interested in something like this? Anyone interested in giving it a go?

**Comment by ebaauw** [comment]
5. When status is stopped (after playing a DINGDONG or text-to-speech track) or when there's no longer a signal on the (optical) input (when playing TV or Line-In).

Would even be cooler to subscribe first and catch the autoswitch to TV or Line-In, so we'd finally have an autoswitch back.

So many brilliant ideas - so little time...

**Comment by svrooij** [comment]
💥 👍 😄 🎉 

(Sorry I'm just really happy this is finally implemented!!!)

@ebaauw this might need some tweaking, but from my initial testing this is a solid solution. Could you also test it?

**Comment by svrooij** [comment]
I will be closing this issue right now, as it seems this function does what it is expected to do.
Now available from git install, and in NPM once we release the 1.0.0 version.
