### ISSUE TITLE
About searchMusicLibrary

### ISSUE THREAD

**Issue by olivierjc** [bencevans/node-sonos#228]
There is a problem with the searchMusicLibrary function. Using a colon to separate the type (i.e. A: ALBUM) and the string does not work if you just want to browse the Content Directory. A slash must be used, like that => **A:ALBUM/exact title of your album**.
Also, the string must be encoded with encodeURIComponent (), especially to handle the colons often present in album titles.
The problem, in this case, is that the use of the uPnP Browse function to do a search no longer works (we must replace the spaces with a + which is found encoded by encodeURIComponent () ...) And, unfortunatelly, Sonos didn't have implemented uPnP Search function =(

My suggestion is to split current functions in two:
+ one, searchMusicLibrary () to search with keywords
+ an other one, browseMusicLibrary () to browse the Content Directory

**Comment by svrooij** [comment]
This sound like a good idea, but I don’t really know what you mean. Maybe you can give it a go with a pull-request?

Currently getting everything ready to release v1.0.0, so if you finish your pull-request we will check it out after releasing the new 1.0.0 version. Be sure to use the `sonos-async` branch as your starting point (for now).

**Comment by olivierjc** [comment]
I'm on it, but I have a problem as I don't have any Win computer, so I can't sniff the Sonos Controller...
Browse with this ObjectID = 'A:ARTIST:Halliday' works fine. But 'A:ARTIST:Johnny Halliday' don't work. Same with 'A:ARTIST:Johnny+Halliday' or 'A:ARTIST:Johnny%20Halliday'.
Can you sniff the controller with such a search ? A can't figure which encoding is needed ??

**Comment by svrooij** [comment]
You where right about the encoding, but you're wrong about it not working.

My mac controller just send `A:ALBUMARTIST:chris%20brown` and gets results. And when you search spotify from your Mac controller, it justs queries a spotify server.

I'll fix the encoding part but your pull-request #230 will be rejected.
