### ISSUE TITLE
Issue with searchMusicLibrary() when using custom startIndex

### ISSUE THREAD

**Issue by olivierjc** [bencevans/node-sonos#231]
When using the searchMusicLibrary () function, the startIndex value is ignored and the returned results are always the same.

## Expected Behavior

When the searchMusicLibrary () function is called with a startIndex value other than 0, the result must not be the same as when it is called with a startIndex value of 0 or when no custom value is used.

## Current Behavior

As it stands, however, regardless of the value of startIndex passed as a parameter of the searchMusicLibrary () function, the result is always the same as when the value of this parameter is 0 or no value is passed in. parameter and that the default value is used.

## Possible Solution

The Object.assign () function replaces the extend function of the Underscore library since the last release, but works differently.
Indeed, with this function, the values of the target array are overwritten by the values of the source array when they have the same key.
However, the function is used as follows:
`Object.assign (opts, defaultOptions);
`which means that the default values override the values passed in parameters to the searchMusicLibrary () function.
It should be used in this way:
`Object.assign (defaultOptions, opts);
`thus, values passed in parameters to the searchMusicLibrary () function will override the default values.

## Sample code or executed example

```
sonosMain.factory('library', function() {

  let ftn = [];

  ftn.get = function () {
    return {
      label: 'Bibliothèque',
      type: 'library',
      content: [
        {label: 'Artistes', code: 'albumArtists', template: 'sources_category'},
        {label:'Albums',code:'albums', template: 'sources_album'},
        {label:'Compositeurs',code:'composers', template: 'sources_category'},
        {label:'Genres',code:'genres', template: 'sources_category'}
      ],
      details: ' hide',
      icon:'M3 13h2v-2H3v2zm0 4h2v-2H3v2zm0-8h2V7H3v2zm4 4h14v-2H7v2zm0 4h14v-2H7v2zM7 7v2h14V7H7z'
    }
  };

  ftn.browse = async function(device, content, startIndex, browseString) {
    if (!browseString) {
      return await device.getMusicLibrary(content.code, {start: startIndex, total: 100});
    } else {
      browseString = encodeURIComponent(browseString);
      if (content.code === 'genres') {browseString = browseString + '/'};
      let data = await device.searchMusicLibrary(content.code, browseString, {start: startIndex, total: 100}, '/');
      if (startIndex === 0 && data.items[0].title === 'All') {data.items.splice(0,1)};
      return data;
    }
  }

  return ftn;

})
```

## Versions (and Environment)

**Node version**: v8.9.4
**node-sonos version**:  1.0.0
**OS**: Ubuntu 17.10

**Comment by olivierjc** [comment]
I think this is the solution :

**Current code :**  `Object.assign(opts, defaultOptions)`, where values in defaultOptions overrides user values in opts.

**Correct code :**  `Object.assign(defaultOptions, opts)`, where uer values in opts overrides defaults values in defaultOptions.

**Comment by svrooij** [comment]
How come your issue isn't as nicely formatted as the template? This would qualify as a smallish issue.
And there is a problem with it anyway.

Instated creating tests against a real sonos device and once you enable this row it will crash mocha.
https://github.com/bencevans/node-sonos/blob/0803384549e098b1c999d33c099720dcf75bf083/test/sonos.test.js#L374

The search thingies will get my attention this weekend.

**Comment by olivierjc** [comment]
Sorry for bad formatting. I fixed it.
