### ISSUE TITLE
SMAPI Implementation

### ISSUE THREAD

**Issue by olivierjc** [bencevans/node-sonos#233]
This is not an issue, so I don't use the template =).

As I'm working on a Controller to manage my Sonos System with my Linux laptop, I want to be able to use SMAPI for music services instead of specifics API of each service. Don't seem too hard.

My problem is to get a list of accounts registered in the Sonos System.

SOAP action GetStringX with {VariableName: 'R_SvcAccounts'} is used by official controller, but it returns an encrypted string which I can't decrypt so far.

Is there another way to get theses accounts ? I saw in different places that a GET request on 'http://{ip.Address}:1400/status/accounts' is used, by it returns no accounts (I have a Deezer Premium account).

**Comment by svrooij** [comment]
I don't even see traffic from the controller to my sonos. Thinking it talks directly to the spotify api. 

You could check out the [services folder](https://github.com/bencevans/node-sonos/tree/master/lib/services). Each service got a `SCPDURL` if you put that after the url of you sonos `http://192.168.x.x:1400` you get the service documentation. Ben imported these like a long time ago, maybe they made some changes to it. So there might be some functions that are not in this library.

Implementing it through SMAPI would be better then implementing the all the music api's separate.

**Comment by olivierjc** [comment]
SMAPI is well documented on Sonos Lab, and so really easy to implement. So far, I can browse containers and start playing albums, playlists, streams, etc... The controller talk with music service with SMAPI, and use the AddURIToQueue SOAP action to add media to queue, with classic metadata. Then, the player do the stuff to get metadata from the music service. It works well =)

**BUT** my user name for Deezer or Qobuz (TuneIn is anonymous) is hard coded =(

After some investigations, I found that Sonos made changes some times ago for security purposes, so data about accounts is now crypted. The controller gets this data with GetStringX, as I said.

So, it seems there is only two options:
- cracking R_svcAccounts value... I can't figure how, and anyway, doing so may raise legal issues.
- just ask user name for each music service, which is not really user friendly...

**Comment by svrooij** [comment]
Do you have any links to those docs?

And care to share some code on how you done this?

My controller does a request to [MediaService](https://github.com/bencevans/node-sonos/blob/master/lib/services/MusicServices.js#L28) `ListAvailableServices` maybe that could work.

**Comment by olivierjc** [comment]
[The link to SMAPI documentation](https://musicpartners.sonos.com/?q=docs).

I will post some code when I'm home this evening.

The request to `ListAvaliableServices ` returns the whole list of avalaible music services, with many informations (id, name, API url, secure API url, authentication method...), but no information whether an account is registered in Sonos system.

**Comment by olivierjc** [comment]
I will post my code later, as I'm facing some issues. I wrote it in my controller, using $http from AngularJS, so I try to use request-promise-native instead, but so far it didn't work (I got a blank result: not null or undefined, just blank...) I'm going to investigate a little more to give a code compatible with node-sonos.

**Comment by svrooij** [comment]
@olivierjc you got something to work with?

If you got something to share you can always reopen this issue.
