### ISSUE TITLE
Player in group reports playing while group is paused

### ISSUE THREAD

**Issue by svrooij** [bencevans/node-sonos#234]
If you ask a player that isn't the coordinator of the group what the playing state is, it will always tell you it is playing.

## Expected Behavior

I would expect all the players in a group to respond the same to the getcurrentstate function

## Current Behavior

- Player 1 (group coordinator)
- Player 2 (member)

- Player 1 `getCurrentState()` === `paused`
- Player 2 `getCurrentState()` === `playing`

## Possible Solution

Maybe we could implement something that would show the state of the group if it was a member.

## Sample code or executed example

1. `SONOS_HOST=192.168.x.10 node examples/getstate.js`
2.`SONOS_HOST=192.168.x.11 node examples/getstate.js`

## Versions (and Environment)

**Node version**: 8.7.0
**node-sonos version**: 1.0.1
**OS**: MAC

**Comment by olivierjc** [comment]
I don't think this is a bug.
When a player is grouped, its `AVTransportURI `is `x-rincon{UUID of coordinator}`.  And even if the coordinator is paused, players in its group still play this URI... Actually, a group is never paused: it's just the coordinator.

As far as I can sniff, this is the same for official controller.

**Comment by Rolf-M** [comment]
Hello together,
I found out, that it‘s not only the state, returned By the api but as well the state you send to a speaker.
If you group a speaker and press the Play/pause Button on whatever speaker in the group, it‘ll pause/Play on all of them.
If you do it with the Node-Sonos, it‘ll make a difference. On the coordinator everything is find. On other speakers, pausing one will lead to a not expected state, not showing in the official controller.
So, from there, i would say yes, the play state of the group (the one send and returned) has to Go to the coordinator and this has to be treated By the api.
Regards Rolf

**Comment by svrooij** [comment]
I'll be focusing my efforts on my [typescript](https://github.com/svrooij/node-sonos-ts) version of this library. The new project is inspired by the stuff discussed here.

Closing this issue (for now).
