### ISSUE TITLE
joinGroup finds wrong device

### ISSUE THREAD

**Issue by Nemesis353** [bencevans/node-sonos#241]
joinGroup only looks for for device name. i have a group of speakers (playbar, sub, 2x surrounds) in my group bedroom so it names all the devices bedroom. when i try to join office with bedroom it joins the wrong device.

joinGroup should join the device coordinator and not the first one it finds

sonos.js - Sonos.prototype.joinGroup - line 268

const zoneInfo = result.zones.find(z => z.name.toLowerCase() === otherDeviceName.toLowerCase());

should become

const zoneInfo = result.zones.find(z => z.name.toLowerCase() === otherDeviceName.toLowerCase() **&& z.coordinator === 'true**');

**Comment by svrooij** [comment]
I've been checking the code for this, but I don't have that setup here. I was in the understanding that all the group members have the same group Id. And [this part](https://github.com/bencevans/node-sonos/blob/master/lib/sonos.js#L272-L275), should get the correct group ID even if the device you want to join isn't the coordinator.

Could you might send me the output of the following code?
```
const Sonos = require('../').Sonos
const sonos = new Sonos(process.env.SONOS_HOST || '192.168.96.53')
sonos.getTopology().then(result => {
  console.log(result.zones)
}).catch(err => {
  console.log('Error joining device %j', err)
})
```

**Comment by svrooij** [comment]
I added an extra parameter, that still allows for the original behavior, but also lets you join the devices correctly.

Please re-open if you still think this is an issue.
