### ISSUE TITLE
selectTrack(trackNo) raises UPnP error 711

### ISSUE THREAD

**Issue by magnlund** [bencevans/node-sonos#242]
After playing URI using the setAVTransportURI(uri) function UpnP err 711 is being raised. In earlier version I used the playWithoutQueue function.

Sonos should resume the selected selected song in the queue given by the queuePosition number

UpnP err 711 is being raised.

## Sample code or executed example
const       promise1 = sonos.selectQueue(),
                promise2 = sonos.selectTrack(queuePosition),
                promise3 = sonos.setVolume(volume),
                promise4 = sonos.play();
        
        Promise.all([promise1,promise2,promise3,promise4])
        .then (values => { <And so on>

queuePosition is the the number retrieved from the function currentTrack before setAVTransportURI(uri) was called. The only queuePosition number that seems to be accepted is #1. Numbers >1 raises the error.

## Versions (and Environment)
**Node version**: 8.9.3

**node-sonos version**: 1.1.1

**OS**: Win10

**Comment by magnlund** [comment]
After playing URI using the setAVTransportURI(uri) function UpnP err 711 is being raised. 
The code block where this happens looks like this:
 const      promise1 = sonos.selectQueue(),
                promise2 = sonos.selectTrack(queuePosition),
                promise3 = sonos.setVolume(volume),
                promise4 = sonos.play();

Where queuePosition is the the number retrieved from the function currentTrack before setAVTransportURI(uri) was called. The only queuePosition number that seems to be accepted is #1. Numbers >1 raises the error.

**Comment by svrooij** [comment]
I don't think this i the correct way to execute those 4 promises.
If you want to chain them you could have a look [here](https://javascript.info/promise-chaining). Do you still need any help? Since you closed this issue yourself

**Comment by magnlund** [comment]
Hi Stephan!
Finally I realized my bad approach, I don’t think it was a bug really😉
 I solved it though by copying your playNotification function and made some changes to fit into my special needs. Now it works like a charm.
Thank you for responding and also for a GREAT API.

Regards
Magnus Lundberg
______________________________________
Magnus Lundberg
Mobile: +46 730 23 09 36
Email: contact.magnus.lundberg@gmail.com

Från: Stephan van Rooij
Skickat: den 25 mars 2018 13:43
Till: bencevans/node-sonos
Kopia: magnlund; State change
Ämne: Re: [bencevans/node-sonos] selectTrack(trackNo) raises UPnP error 711(#242)

I don't think this i the correct way to execute those 4 promises.
If you want to chain them you could have a look here. Do you still need any help? Since you closed this issue yourself
