### ISSUE TITLE
getName() no longer available

### ISSUE THREAD

**Issue by kimaldis** [bencevans/node-sonos#253]
Having discovered a device, is there a way to get the device's name?

many thanks.

**Comment by svrooij** [comment]
With the big migrate to async, I apperantly removed it, 😬.....

It should be in sonos.getZoneAttrs(), [here](https://github.com/bencevans/node-sonos/blob/b5647b2359f1bb5575354dbe913c59a16effc225/lib/sonos.js#L437)

Will add the getName function back in soon.

**Comment by kimaldis** [comment]
that was it. Thanks.
