### ISSUE TITLE
sonos.queueNext is not a function

### ISSUE THREAD

**Issue by htilly** [bencevans/node-sonos#265]
When calling "sonos.queueNext" I get the response:
"TypeError: sonos.queueNext is not a function"

Used syntax in the example:
https://github.com/bencevans/node-sonos/blob/master/examples/queuenext.js

Btw, great with all the examples =)

Add the track as next in queue =)

1.
2.
3.
4.

## Versions (and Environment)

**Node version**: v9.11.1
**node-sonos version**: "sonos": "^1.1.2"
**OS**: RHEL7

**Comment by svrooij** [comment]
The [old code](https://github.com/bencevans/node-sonos/blob/v0.x/lib/sonos.js#L816-L836) says it is just a call to [setAVTransportURI](https://github.com/bencevans/node-sonos/blob/master/docs/sonos.md#sonossonossetavtransporturioptions).

So the old sample has to be replaced with a call to `setAVTransportURI`

**Comment by htilly** [comment]
Thanks, works!

Tilly
