### ISSUE TITLE
Help - RemoveTrackFromQueue

### ISSUE THREAD

**Issue by htilly** [bencevans/node-sonos#266]
Hi again =)

How can I call the following function?
https://github.com/bencevans/node-sonos/blob/f3e85296ffbebc4baeb3960b52e6ac31744e4309/lib/services/AVTransport.js#L63

var track = 3
sonos.RemoveTrackFromQueue(track).then(success => {
      _log('Removed the following track from the queue:' + track)
    }).catch(err => { _log('Error occurred: ', err) })

TypeError: sonos.RemoveTrackFromQueue is not a function

## Sample code or executed example

1.
2.
3.
4.

## Versions (and Environment)

**Node version**: v9.11.1
**node-sonos version**: sonos@1.1.2
**OS**: RHEL7

**Comment by svrooij** [comment]
@htilly Al the functions in the `lib/services` folder are "expert" functions. Not everything is implemented/documented in the library, but you could use it by getting a `AVTransport` with:
```node
var avtransport = sonos.avTransportService();
avtransport.RemoveTracksFromQueue(options);
```

We use the `AVTransport` in the lib as well, for example [here](https://github.com/bencevans/node-sonos/blob/master/lib/sonos.js#L218-L222).
So you'll need to find out what parameters you'll have to send, by opening the xml `http://[ip_sonos]:1400/xml/AVTransport1.xml`.
And if your found the correct parameters you could maybe add the documentation to [AVTransport.js](https://github.com/bencevans/node-sonos/blob/master/lib/services/AVTransport.js#L63) so we could implement it in the main lib as well.

**Comment by htilly** [comment]
Ok, thanks for the fast reply. Could you help me a little bit further..
So I got the XML (converted to JSON):
{
					"name": "RemoveTrackFromQueue",
					"argumentList": {
						"argument": [
							{
								"name": "InstanceID",
								"direction": "in",
								"relatedStateVariable": "A_ARG_TYPE_InstanceID"
							},
							{
								"name": "ObjectID",
								"direction": "in",
								"relatedStateVariable": "A_ARG_TYPE_ObjectID"
							},
							{
								"name": "UpdateID",
								"direction": "in",
								"relatedStateVariable": "QueueUpdateID"
							}
						]
					}
				},

So this would translate to something like:

  var avtransport = sonos.avTransportService()
  avtransport.RemoveTracksFromQueue(0, 'Q:0/5', 0)

I still receive TypeError: avtransport.RemoveTracksFromQueue is not a function when running :(

Found some good definitions and explanation over here:
https://gowalker.org/github.com/ianr0bkny/go-sonos/upnp#AVTransport_RemoveTrackFromQueue

/Tilly

**Comment by svrooij** [comment]
Closing this issue for now, please re-open if you still got a problem
