### ISSUE TITLE
Retrieve active subscriptions from ZonePlayer

### ISSUE THREAD

**Issue by ebaauw** [bencevans/node-sonos#285]
Do you know if it's possible to get an overview of all active event subscriptions from a ZonePlayer?

Several firmware versions ago, this information was displayed in the ZonePlayers `/status` page, under _upnp_, but that's no longer supported.

**Comment by bencevans** [comment]
I'm not sure that the UPnP protocol provides information on the other clients. Maybe worth running the Sonos debug / troubleshooting with Wireshark running to see if you can spot anything useful there.

**Comment by svrooij** [comment]
@ebaauw what would be the usecase of this question, maybe I can help with this.

Some facts about the subscriptions:
By default every subscription expires 3600 seconds after it is created and not renewed.
In the code this is automatically handled by the listener.
This library requests a timeout of 1800 seconds (30 min) and tries to renew after 25 min, that seemed more stable, because of timescrew.

**Comment by ebaauw** [comment]
Use case: As a paranoid developer, I want to see what subscriptions the Sonos ZonePlayer has registered.  I'm still kinda upset that Sonos killed the debug option.

I'm actually implementing cancelling the subscriptions that homebridge-zp made, when homebridge exits, so no stale subscriptions remain.  I just wanted to check that the subscriptions are indeed cancelled.  Normally the 30 minute lifespan works fine, except when testing, with a lot of restarts.  Cancelling the subscription would allow for longer subscription times, and fewer renewals.

**Comment by svrooij** [comment]
Homebridge-ZP uses this library to communicate to Sonos right?

Have you tried calling, and awaiting, `stopListening()` on the global listener? That should cancel all active subscriptions, and should always be called before you kill the application. That should fix it no matter what. https://github.com/bencevans/node-sonos/blob/master/lib/events/adv-listener.js#L74

It will ignore all unknown subscriptions anyway.

The reason I choose to take a shorter amount of seconds than the maximum of 3600 seconds is that it sometimes isn’t accurate. I never noticed it not working with the current event listener.

**Comment by ebaauw** [comment]
> Homebridge-ZP uses this library to communicate to Sonos right?

Still the old, pre-async version.  I'm still handling the subscriptions myself.  I actually verified that the subscriptions are cancelled, by cancelling them twice and getting an error on the second cancellation.

> I never noticed it not working with the current event listener.

Indeed, it's a very robust mechanism.

**Comment by ebaauw** [comment]
> Just wondering why are you still using the old version?

Time.  Or rather: the lack of it.  Or rather: too much other, more urgent things.  E.g. I first need to create a hook in homebridge, so my plugin gets notified when homebridge is about to exit.  
I do feel bad about it, because I was one of the advocates for the async version.  It is still in the planning for the next major refactor.  No ETA, though.

> But I thing this issue could be closed then?

Yes.

**Comment by svrooij** [comment]
Maybe you’re in luck and you could just bind to the `SIGINT` event. 

https://github.com/svrooij/sonos2mqtt/blob/master/src/bridge.js#L79

**Comment by ebaauw** [comment]
homebridge already does that.  Adding another listener steals the event from homebridge, so it won't exit cleanly.  Also tried the `process.on('exit', () => {...})` hook provided by NodeJS, but that comes too late, as it only supports synchronous calls from the handler.
