### ISSUE TITLE
Question: How to play a playlist.

### ISSUE THREAD

**Issue by ThomasMirlacher** [bencevans/node-sonos#308]
While the examples are really helpful for getting started,
i fail to find an example/documentation on how to queue
and play a playlist (ideally an amazon playlist).

any help would be appreciated!

**Comment by svrooij** [comment]
@ThomasMirlacher you found it already?

The trick I always use myself is, just play it from the App and then extract the data.
Playlists is always tricky, because it actually adds all the songs in a playlist to a new sonos queue.

Maybe you can send us a PR, if you found the solution? Or if that doesn't work for you (you don't know how), just past the code down below between three ``` ` ```

**Comment by ThomasMirlacher** [comment]
@svrooij well, after using tcpdump i do have a solution for this one ...
not clear if it works for everyone out there.

```
// *****
// getting playlist from something like: sonos.getFavorites()

// *****
if (playlist.uri.includes('prime_playlist')) {
	sonos_playAmazonPlaylist(sonos, playlist.title, playlist.uri);
}

// *****
function sonos_playAmazonPlaylist(sonos, title, uri) {
	// this is more a hack for making sonos.queue/Helpers.EncodeXml() happy ...
        // possible improvement: make sure there is no double encoding in EcodeXml()
	uri = String(uri).replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"');
	const parsed = uri.match(/^(x-rincon-cpcontainer):(.*)\?(.*)/).splice(1);

	const region = 51463;

	const metadata = `
	<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/">
		<item id="${parsed[1]}" restricted="true">
			<dc:title>${title}</dc:title>
			<upnp:class>object.container.playlistContainer</upnp:class>
			<desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">SA_RINCON${region}_X_#Svc${region}-0-Token</desc>
		</item>
	</DIDL-Lite>`;

	sonos.flush().then(result => {
		sonos.queue({uri, metadata}).then(result => {
			sonos.selectQueue();
			sonos.play();
		});
	});
}
```

... next thing to work on is how to play a tunein radio station using the information retrieved from sonos.getFavorites()

**Comment by hklages** [comment]
1. Thanks for that. It works fine for my Amazon Prime playlists. 
What is the meaning of "region"? From where does it come from? 

2. Regarding playing a TuneIn radion Station: Extract the radion ID (s12345) and use "playTuneinRadio"
