### ISSUE TITLE
Google Play Playlists

### ISSUE THREAD

**Issue by tylermenezes** [bencevans/node-sonos#327]
Hi! I'm trying to add support for Google Play playlists to `Helpers.GenerateMetadata`, and could use a bit of help. I know that, to play a Google Playlist, the request looks like:

```
const [id] = uri.match(/^x-rincon-cpcontainer:(.*)\?.*/).splice(1)
return {
    uri: String(uri).replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"'),
    metadata: meta.replace('##SPOTIFYURI##', id)
        .replace('##RESOURCETITLE##', title || '')
        .replace('##SPOTIFYTYPE##', 'object.container.playlistContainer')
        .replace('##PARENTID##', '') // optional, can't figure out where it comes from
        .replace('##REGION##', 'SA_RINCON38663_X_#Svc38663-0-Token')
}
```

The problem I'm having now is identifying whether something is a Google Play playlist. All the playlists start with `x-rincon-cpcontainer:1006206c`, but everything past there varies from playlist to playlist. Unfortunately as far as I can tell, all playlists from all services start with `x-rincon-cpcontainer:1006206c`.

The only thing I can find that is consistent across Google Play playlists is `?sid=151&flags=8300&sn=4`. **Could someone with more experience with the Sonos API know if one of those parameters would be a consistent way to identify something as a Google Play playlist?**

Here are a few Playlist IDs for example:
- `x-rincon-cpcontainer:1006206clsZGYBVzMspY87BsVVg0QiBL3iqUxr7jC7Ah6XQhe4Skl0V4PRruNnIZCPgjcP1u?sid=151&flags=8300&sn=4`
- `x-rincon-cpcontainer:1006206c96nxfiXosdG80780z-uLQJqMf-SnUfQxz_egAqj-wqJbiAj5M0CKn5ywWTfG8mZB?sid=151&flags=8300&sn=4`
- `x-rincon-cpcontainer:1006206c8y0BcpohVbM?sid=151&flags=8300&sn=4` (autogenerated "thumbs up" playlist)

**Comment by svrooij** [comment]
We could probably work with the last part.
Are you experienced with Wireshark?

The way I also implement new features is by eastdropping on the communication between the desktop app and the Sonos speakers. Since this communication isn't encrypted (most of the time), you can easily listen in and mimic this behavior.

The easiest to implement a new music service is if you might have a clean dump (Wireshark it) of the commando that actually starts a playlist.

Wireshark outbound http to the ip of the Sonos on port 1400

**Comment by tylermenezes** [comment]
Yep! I got it working using Wireshark captures; the only thing I wasn't sure of is how to uniquely identify it as Google Play, since all the other examples use a prefix rather than a suffix. If you think the URI query string will uniquely identify it, I can submit a pull request.

**Comment by tylermenezes** [comment]
I did some more research into this, and [it looks like SID is a globally unique ID for each music service,](https://groups.google.com/forum/#!topic/python-soco/MkZQ4KWdsp8) so I can match on sid=151. I'll submit a pull request for that once I have a chance. Thanks!

**Comment by svrooij** [comment]
Searching in external music services would also be really nice.
But from my initial findings those requests don't go through the Sonos device, but go straight to the music services api

**Comment by tylermenezes** [comment]
@svrooij I'll open a pull request with what I have so far, but I haven't had time to actually confirm it works. If someone else wants to confirm it works, go ahead, otherwise I'll check this weekend.

FWIW, it would be a lot cleaner overall to check the SID for other services as well, if it doesn't break anything (although Sonos doesn't publish a list anywhere I can find)

**Comment by svrooij** [comment]
Closing this stale issue, you can always re-open this issue if you still want it fixed.
