### ISSUE TITLE
FYI: Sonos developer programme

### ISSUE THREAD

**Issue by ebaauw** [bencevans/node-sonos#331]
FYI, Sonos announced a new developer programme, to be launched Sept 6.  See 
https://developer.sonos.com.  I'm hoping for a real (RESTful) API, less XML and more json...

**Comment by svrooij** [comment]
Lets hope they don’t kill the current integrations....

**Comment by ebaauw** [comment]
They launched, see https://developer.sonos.com/build/.  Looks like they provide two different APIs, one for content providers and one for controlling the Sonos players.  The Control API looks RESTful (yes!), but is cloud based (not for me!).  They also mention a control API on the LAN, but that is not yet available.  I'm as excited about this as I am about the Airplay 2 support of my PlayBar.

**Comment by svrooij** [comment]
If you've upgraded to v9.1 you now have [IFTTT](https://ifttt.com) supporting sonos. So you can trigger things right from the cloud.
