### ISSUE TITLE
sonos.getTopology() does not work after upgrading to Sonos version 9.1

### ISSUE THREAD

**Issue by magnlund** [bencevans/node-sonos#332]
After upgrading to Sonos Version 9.1 sonos.getTopolgy() does not work anylonger and therefore sonos.JoinGroup() fails

## Expected Behavior
http://IP_ADRESS:1400/status/topology seems to be empty and therefore sonos.getTopology() fails with error message "Cannot read property 'ZonePlayer' of undefined"

## Possible Solution
I would really like an update on this cause grouping management is essential in my HA setup. Thanks in advance

## Versions (and Environment)
**Node version**: 8.9.3
**node-sonos version**: 1.4.1
**OS**:

**Comment by ebaauw** [comment]
This got me scared, but it looks like homebridge-zp is still working.  Please be aware that upgrading the ZonePlayer causes it to reboot, losing all subscriptions.  There's no notification (that I've seen, or handle) to clients with an open subscription, so effectively clients are no longer receiving events until they renew the subscription or are restarted.

**Comment by magnlund** [comment]
Thanks for your quick respons. If I got you correct I need to restart the CLIENT. I tried to factory reset all my players but that did not help. Please confirm.

**Comment by magnlund** [comment]
This Seems to be tricky. I have done factory reset on all my 3 players and restarted my Rpi. Stil the same issue. Morse tip are highly appreciated cause I really rely on your script in my HA setup. I have 2 connect amps and one Sonos One

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by magnlund** [comment]
Please find this thread. It comes from node-sonos. The next came from you as well but from zonebridge

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ebaauw** [comment]
> http://IP_ADRESS:1400/status/topology

These are undocumented debug pages, and have been known to change unannounced.  Best not base node-sonos (or any client) on this.  Use the `zoneGroupTopology` service instead.

**Comment by magnlund** [comment]
Makes sense but this is the adress which is being used by getTopology() in sonos.js. I would be extremely happy if a new updated version of sonos.js could be released because joinGroup() does NOT work with sonos 9.1

**Comment by magnlund** [comment]
Just installed 1.5.0. Works like a charm. Thank you SO MUCH for this quick response

**Comment by jcleek** [comment]
Can you tell me how exactly you installed the new version and got it to work? I have tried both packages listed by bencevans and neither cause it to work. Homebridge crashes on SONOS.

**Comment by magnlund** [comment]
Just to clarify. This is about node-sonos 1.5.0; not homebridge.
After release of 1.5.0 yesterday evening i simply did this:
-Changed  my package.json file to 1.5.0
- Installed 1.5.0 via npm install

**Comment by jcleek** [comment]
ah, ok. Thank you sir. Hopefully someone smarter than me can get this working with homebridge.
