### ISSUE TITLE
playTuneinRadio(stationId, stationTitle) does not work after upgrading to Sonos 9.1

### ISSUE THREAD

**Issue by magnlund** [bencevans/node-sonos#333]
playTuneinRadio(stationId, stationTitle) does not work after upgrading to Sonos 9.1

## Current Behavior
Sonos returns error message unknownMediaRequest

## Possible Solution
I would really appreciate a new version of this great API supporting Sonos 9.1

## Versions (and Environment)

**Node version**: 8.9.3
**node-sonos version**:  1.4.1
**OS**:

**Comment by svrooij** [comment]
Still working over here.

You can verify by typing the following in the terminal in the root of the sonos lib. (Be sure to replace your ip).

```bash
SONOS_HOST=192.168.x.x node examples/playTuneinRadio.js
# Or with debug
SONOS_HOST=192.168.x.x DEBUG=sonos* node examples/playTuneinRadio.js
```

Please put the output of the above command in a comment, if it isn't working for you.

**Comment by magnlund** [comment]
Thanks for respons! The problem is now resolved! All TuneIn station IDs seem to require a leading "s" which was not the case until a week ago. I simply updated all my stationIDs with  that and now it works. As you said this was not related to Sonos;) What are the plans regarding resolving the grouping issue that I previouesly registered?

Regards
Magnus Lundberg
__________________________________
Magnus Lundberg
Phone: +46 730 23 09 36
Email: contact.magnus.lundberg@protonmail.com

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
