### ISSUE TITLE
Event volume not firing after setVolume 

### ISSUE THREAD

**Issue by ptorrent** [bencevans/node-sonos#339]
Hello,

Event "volume" not firing after setVolume( x ) ?

```javascript
        listener.subscribeTo(device).then(result => {
		console.log('Manually subscribed to sonos events')
	})
	listener.on('Volume', volume => {
		console.log('VOLUMNE UPDATED',volume)
	})
        device.setVolume(2).then(result => { conosle.log('ok') })
```
Only thoses events seems to work : 

```javascript
	listener.on('AlarmClock', result => {
		console.log('Alarms changed event %j', result)
	})				
	listener.on('ZoneGroupTopology', result => {
		console.log(JSON.stringify(result))
	})
```
Thanks for support !

**Comment by svrooij** [comment]
There are two different event emitters.
One global event emitter (for group / alarm changes), the one you're referring to.

And every device is an event emitter as well, for events specific to that device. The way it works is that if you subscribe to a event on the device itself, it will create the listener automatically.

There also is a sample in the sample folder, that last time I checked, worked perfectly.

If you still got any questions feel free to re-open this issue.
