### ISSUE TITLE
Destroy sonos device ?

### ISSUE THREAD

**Issue by ptorrent** [bencevans/node-sonos#341]
Hello there !

Is there a way to destroy Device like device.destroy (listeners, etc.... )

Is it possible to know when a device is disconnected ?

Thanks for support !

**Comment by bencevans** [comment]
`device.stopListening()` should do the trick.

**Comment by svrooij** [comment]
Or check out the event sample https://github.com/bencevans/node-sonos/blob/master/examples/events.js
