### ISSUE TITLE
Error since sonos firmware update (since cloud api)

### ISSUE THREAD

**Issue by WeeJeWel** [bencevans/node-sonos#344]
```
TypeError: Cannot read property 'ZonePlayer' of undefined
    at request.then.then.result (/node_modules/sonos/lib/sonos.js:563:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Seems like `info.ZonePlayers` is undefined.

**Comment by svrooij** [comment]
Sadfully Sonos removed this endpoint in v9.1
That is why it’s deprecated 
https://github.com/bencevans/node-sonos/blob/09673a7ba722c0ad56a8054925b1adff369eaaad/lib/sonos.js#L550

As stated in the readme, all libraries depending on getTopology() should migrate to `getAllGroups()`. 
https://github.com/bencevans/node-sonos/blob/master/lib/sonos.js#L245-L249

Is this library used in the Homey Emile?

**Comment by WeeJeWel** [comment]
Thank you!
