### ISSUE TITLE
cannot get eventlistener to work.

### ISSUE THREAD

**Issue by AxelDolislager** [bencevans/node-sonos#355]
For the past 4 hours I've been tweaking around in my project trying to get the eventlistener to work.
I'm also using https and socketio, but that wouldn't be the problem I guess.

Can someone please tell me what I'm doing wrong?
Right now I just have this in my index.js file with everything else commented out.

```
const { Sonos } = require('sonos')
const listener = require('sonos').Listener
const sonos = new Sonos('192.168.1.148')

listener.startListener()
listener.subscribeTo(sonos).then(function(result){
    console.log('Manually subscribed to sonos events')
})
sonos.on("currentTrack", function(track){
    console.log(track);
})
```

Thanks!

**Comment by svrooij** [comment]
Hi Axel,
I think it might be an issue that you try to start the listener without it having at least one some device.

Not even sure why the manual starting of the listener is even supported (aka why tha f... did I build it).

I would just use the last statement, it will automatically setup the listener without you having to do anything.

So start with `sonos.on(".....")` and just skip the startListener and the subscribeTo parts

**Comment by AxelDolislager** [comment]
Hey @svrooij thanks for replying!

Right now I'm trying it like this:

```
const { Sonos } = require('sonos')
const sonos = new Sonos('192.168.1.148')

sonos.on("CurrentTrack", function(track){
        console.log(track);
})
```

But this also doesn't seem to work.
I usually play with spotify, is that also supported or should i use the spotify api for that?

Thanks again!

**Comment by svrooij** [comment]
Could you try the following.

1. Check-out this repository and open the folder
  `git clone https://github.com/bencevans/node-sonos.git && cd node-sonos`
1. Run `npm install`
1. Run `SONOS_HOST=192.168.1.148 node examples/events.js` and see what happens.

That works here, I'm running Node v8.7.0 and my sonos is on version 9.2

**Comment by svrooij** [comment]
What OS are you using?

For the event listener to work, it will automatically setup a small http server on port 4000 (overridable by setting `SONOS_LISTENER_PORT`).
This http server is then used as an endpoint for the notifications.

So it should be reachable from the sonos system (and not be blocked by the firewall on your PC).

**Comment by AxelDolislager** [comment]
I don't know what I did, but it seems to work now!
Thanks for your help!

**Comment by orensharon** [comment]
Hi @svrooij 
I faced the same exact issue for the last few hours - I didn't receive any event using the `sonos.on(..)`. 
I Tried all of the above, nothing helped.

Finally, I figured it out.. 

When I looked at `adv-listener.js` I saw the following:
`const listenAddress = process.env.SONOS_LISTENER || ip.address('public')`
I tried to set the value of `SONOS_LISTENER=192.168.68.52`  and that did the trick!

192.168.68.52 is the local IP address of the server host machine. 
It's where this app is running and listening on port 4000.

My questions are:
1. `ip.address('public')` shouldn't auto set that IP address I just set manually?
2. There is any solution to get this work without set the IP manually?

**Comment by svrooij** [comment]
> ip.address('public') shouldn't auto set that IP address I just set manually?

Yes, but it picks the first IP found. You probably have multiple network adapters (maybe virtual like docker/VM/??)

> There is any solution to get this work without set the IP manually?

No, this is the solution if the IP isn't discovered automatically.

I'm no longer maintaining this library, I moved all my apps to [node-sonos-ts](https://svrooij.io/node-sonos-ts/). Where I re-wrote the [events-part](https://svrooij.io/node-sonos-ts/sonos-device/events.html). This also [supports](https://github.com/svrooij/node-sonos-ts/blob/a79e92852e4e7e47fb12fb219db59efdc061eeb5/src/sonos-event-listener.ts#L27-L57) setting the correct interface to get the first IP from that specific interface.

**Comment by orensharon** [comment]
You are right. I disabled all the VMs network adapters and it's working correctly.
I will follow the new repository.
Thanks
