### ISSUE TITLE
Timeout fires in test invalidating later tests

### ISSUE THREAD

**Issue by ludlovian** [bencevans/node-sonos#362]
In fixing #359, I noticed that some of the later tests failed randomly.

In an earlier test, a timeout is set to `assert(fail)` after 100ms to catch the situation where a `DeviceDiscovery` does not issue a `timeout` event when it should.

If the test passes, then the rogue timeout is left hanging to fire 100ms later, disrupting later tests.

https://github.com/bencevans/node-sonos/blob/851a5355cd014d794b3887ce74dee1cc3cacdef1/test/sonos.test.js#L314-L327

PR to fix on the way

**Comment by svrooij** [comment]
Next time if you type `Fixes #362` in the commit, it will automatically close the issue when the PR is accepted.
