### ISSUE TITLE
sonos.play(uri) results in a CORS error.

### ISSUE THREAD

**Issue by wwwizzarrdry** [bencevans/node-sonos#365]
**sonos.play(uri) results in a cors error.**

> Access to fetch at 'http://192.168.2.124:1400/MediaRenderer/AVTransport/Control' from origin 'http://192.168.2.8:8010' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

```
const sonos = require('node-sonos');
const Sonos = new sonos.Sonos('192.168.2.124', 1400);
const uri = 'http://192.168.2.115:32400/library/parts/316688/1458393932/file.mp3';

Sonos.play(uri, function (err, playing) {
   console.log([err, playing])
});

```
The file plays fine
![image](https://user-images.githubusercontent.com/2218144/48720595-09fe1800-ec31-11e8-9f67-d821e26e7dd7.png)

And when I run the same command without Vue+Webpack it works. Is there something about vue or webpack that changes the headers to no cors?

**Comment by ebaauw** [comment]
This reads like a firewall blocking the connection from 192.168.2.8 (presumably where your node Sonos client runs) to the Sonos zoneplayer, _not_ from your Sonos zoneplayer to the library on 192.168.2.115.

**Comment by ebaauw** [comment]
Are you running the Sonos client in a web browser?  Then you need to provide an additional HTTP header to allow the Javascript to access another server then from which it was loaded.  See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.

**Comment by svrooij** [comment]
I don’t think package is build to be used in the browser.
If you want to control it from a website (or whatever) you’ll have to control it from the node proces.

So the controls go web browser -> node proces -> sonos

**Comment by wwwizzarrdry** [comment]
That makes sense as it it works when I test it as a one-liner from the examples, and not from my web app.

So I should create a spawn a separate http server for Sonos to listen on? Similar to how you would run a socket server alongside another app running on another port. I.E. like in `/examples/nowPlayingWebsite.js`

**Comment by svrooij** [comment]
No you should create a seperate http server where your web application talks to and then sends those commands to the chosen sonos speaker.

I would suggest create an [ExpressJS](https://expressjs.com/en/starter/basic-routing.html) application with endpoint like `/play` and `/stop` then you got control over all the headers and you can just control your sonos speaker from the web-application.

You can also checkout [Sonos2mqtt](https://github.com/svrooij/sonos2mqtt) that is a small application that forwards sonos messages to mqtt and lets you control sonos by sending specific commands to mqtt.

I'm just curious, what are you trying to accomplish?

**Comment by wwwizzarrdry** [comment]
Thanks, that how I have it working now. Wanted to find a way to avoid running a separate sonos server. 

@svrooij 

> I'm just curious, what are you trying to accomplish?

I'm just making a Plex clone, that has Sonos support build in.
<img width="802" alt="1a" src="https://user-images.githubusercontent.com/2218144/48783066-9ae7f880-ecf0-11e8-9b6d-ce9d73913e6d.PNG">
<img width="802" alt="1b" src="https://user-images.githubusercontent.com/2218144/48783081-a2a79d00-ecf0-11e8-9b30-d4ab37eaeb23.PNG">
<img width="805" alt="1c" src="https://user-images.githubusercontent.com/2218144/48783089-a76c5100-ecf0-11e8-9467-47edb228e033.PNG">

**Comment by bencevans** [comment]
@wwwizzarrdry this is a limitation by the Sonos api we use. It doesn't support CORs as far as we are aware. You would need to proxy the requests through a separate server that adds the CORs headers.
