### ISSUE TITLE
Unable to remove track(s) from queue

### ISSUE THREAD

**Issue by wwwizzarrdry** [bencevans/node-sonos#368]
I assume we have to implement this with `request(endpoint, action, body, responseTag)`

Any idea what action Sonos is expects when you remove a selected track?

**Comment by svrooij** [comment]
This can be done by calling one of the things in the `AVTransport` service.
https://github.com/bencevans/node-sonos/blob/master/lib/services/AVTransport.js#L63

Will have a look into the needed parameters.

**Comment by wwwizzarrdry** [comment]
Thanks for pointing this out. An essential resource to be aware of.

**Comment by svrooij** [comment]
@wwwizzarrdry just took the time to implement removing files from the queue.

Now I can finally create an **Auto remove artist x from queue**-script

**Comment by svrooij** [comment]
🎉 
@wwwizzarrdry you can now Remove 1 or multiple songs from the queue.

**Comment by wwwizzarrdry** [comment]
That's huge! Going to make a lot of people happy today ;)
