### ISSUE TITLE
Subscribe to Stream Updates aka reportPlaySeconds

### ISSUE THREAD

**Issue by wwwizzarrdry** [bencevans/node-sonos#370]
Can't subscribe to changes in `currentTrack`. 

For example, listen for changes to  `CurrentTrack`.`position`. The only way to capture position updates currently is to poll 'currentTrack' every second when a Play event is heard, and clear the polling when a Pause or Stop event is caught.

The Sonos API already broadcasts this information as documented here: https://musicpartners.sonos.com/?q=node/488

And more specifically, here: `reportPlaySeconds`
https://musicpartners.sonos.com/node/388

**Comment by svrooij** [comment]
The Sonos api is something totally different, the only released it very recently and isn't really opened up.
You could also use a local timer and sync with sonos once every minute.

Closing this for now, if you want to have this implemented in node-sonos you can always open this ticket again.
