### ISSUE TITLE
How set group volume

### ISSUE THREAD

**Issue by wwwizzarrdry** [bencevans/node-sonos#373]
How to you set the volume for a group of speakers with `sonos.setVolume()`
Are you supposed to loop through all zones returned from `getAllGroups()` and set volume explicitly for each?

**Comment by bencevans** [comment]
Yes. Essentially the Sonos app sends a command to each device to update the volume when you change the "group volume".

**Comment by ebaauw** [comment]
Actually, the Sonos app sends a `setGroupVolume` command to the `GroupRenderingControl` service.  You need to instantiate the `GroupRenderingControl` service and invoke it’s `_request()` method to do the same.

**Comment by bencevans** [comment]
Ah i stand corrected. Thanks @ebaauw!

**Comment by wwwizzarrdry** [comment]
So would that be done like this? 

`const { GroupRenderingControl } = require('sonos');`

or

`const group = new sonos.GroupRenderingControl(host, port);`

**Comment by ebaauw** [comment]
Something like:
```
const sonos = require(‘sonos’)
const group = new sonos.Services.GroupRenderingControl(host, port)

const args = {
  InstanceID: 0,
  DesiredVolume: volume + ‘’
}
group._request(‘setGroupVolume’, args).then(...)
```

I’m still using the old callback version of node-sonos (so much to do, so little time...), but if you see past that, here’s an example:
https://github.com/ebaauw/homebridge-zp/blob/c9e04ea3accdf5a3d0c1bfd3c09da56db8fd0254/lib/ZpAccessory.js#L132
https://github.com/ebaauw/homebridge-zp/blob/c9e04ea3accdf5a3d0c1bfd3c09da56db8fd0254/lib/ZpAccessory.js#L777-L789

**Comment by ebaauw** [comment]
Note the sonos API documentation for each service is on the zoneplayer itself, 
`http//`_ipaddress_`:1400/xml/GroupRenderingControl1.xml`.  The services are listed in the `device_description.xml`, which is referred to from zoneplayer’s the UPnP messages.

**Comment by wwwizzarrdry** [comment]
@ebaauw A huge help, thanks for taking the time to spell this out for me. My current implementation is so poor, this will make a big difference.

**Comment by believer** [comment]
@ebaauw have you encountered weird behavior when using this API? It seems like some speakers are set to the `DesiredVolume`, but others are increased/decreased. My implementation looks something like this

```
new Sonos.Services.GroupRenderingControl('192.168.110.100')
  ._request('SetGroupVolume', {
    InstanceID: 0,
    DesiredVolume: '10',
  })
  .then(status => {
    console.log(status)
  })
```

**Comment by ebaauw** [comment]
The relative volumes of the members are more or less respected when changing the group volume.  Also when you change the player volume of a member, the group volume is adjusted.  This behaviour can also be observed using the Sonos app.

**Comment by svrooij** [comment]
@ebaauw when Will you be migrating to the new async version for node-sonos?

**Comment by ebaauw** [comment]
I'm slowly but surely refactoring all my homebridge plugins to use the dynamic platform accessory model.  At the same time, I'm moving all the generic code into a common library, based on async functions, classes and events, rather than callback functions and prototypes.  I started with the simplest plugin - my virtual weather station.  It's almost where I want it to be, I'll be doing my smart meter plugin next.  The Sonos and Hue plugins are technically most complex, so I'll do them latest.

This are all hobby projects, so it will take some time.

Why your question?  Is there any need for me to speed up the migration?

**Comment by svrooij** [comment]
Just curious. We could use some active developers for this project as well. And I spend a lot of time on the async version of node-sonos, and we’ll only make updates to the async version. As of last month I implemented a way to have an event when the group configuration changes, that would greatly beneficial for your bridge as well.
