### ISSUE TITLE
Q: How to determine if zone supports balance?

### ISSUE THREAD

**Issue by ebaauw** [bencevans/node-sonos#402]
Has any-one been able to figure out how the Sonos app determines when to show _Balance_ in the _EQ Settings_?  I find that it does so for Stereo pairs as well as for the Sonos Connect, but not for Home Theatre Setups (like the PlayBar).

For now, I'm whitelisting zoneplayers that natively support stereo channels (like the Connect), and home theatre zoneplayers (like the PlayBar).  I'm assuming a zone with slave zoneplayers where the master zoneplayer isn't a home theatre system must be a stereo pair.  See https://github.com/ebaauw/homebridge-zp/issues/64#issuecomment-471288785.

**Comment by svrooij** [comment]
I don't have a setup to test this, but what we always do is start wireshark to listen on port 1400 and then execute the wanted command and build it in node.

Closing for now, if anyone knows an answer please let us know
