### ISSUE TITLE
Q: How to determine what music provider is playing

### ISSUE THREAD

**Issue by viktorgardart** [bencevans/node-sonos#405]
Is there a way I can receive the content provider from whom the music is played from? (See image).

![IMG_0022](https://user-images.githubusercontent.com/6084484/54865173-cdb70180-4d61-11e9-838a-d645ba444fc0.jpg)

**Comment by Villarrealized** [comment]
I’ve wondered that myself, but I haven’t seen anything explicit with the data that Sonos sends when inspecting through wireshark. My guess is they determine the provider based on the song’s uri.

**Comment by viktorgardart** [comment]
Thanks for the reply! 

After some debugging it seems that there's a `sid` in `TrackURI`. And that `sid` can be mapped to the response of `ListAvailableServices`.
