### ISSUE TITLE
Searching spotify tracks

### ISSUE THREAD

**Issue by svrooij** [bencevans/node-sonos#415]
I was always wondering how Sonos searches for tracks on remote services.
Now I've found out that is uses `https://spotify-v4.ws.sonos.com/` this domain for searching stuff on spotify.

That url also seems to be in [this gist](https://gist.github.com/pascalopitz/9afdc164257ccbb6f4dc22964a92ce66), that lists all the available music services. Also available in the MusicService -> ListAvailableServices

I've also found the WSDL [here](https://musicpartners.sonos.com/sites/default/files/Sonos.wsdl)

So I was wondering if it would be possible to search Spotify (or any other connected services) for tracks. Anyone got any ideas?

**Comment by Villarrealized** [comment]
Interesting. I always assumed they were using the various APIs provided by other music services to do that. That's what I ended up doing for Sonos Web and it works well. Spotify has a great API. I would loathe to deal with the SOAP wrapper that Sonos probably put on it.

**Comment by svrooij** [comment]
@Villarrealized you want to solve this? Closing the issue for now because it seems impossible. You can always re-open if you want to give it a try.
