### ISSUE TITLE
favorite meta data not showing on XM radio channel

### ISSUE THREAD

**Issue by jpoeppelman1** [bencevans/node-sonos#418]
Hello.  I want to be able to invoke play() with URI and meta data from my existing favorites so that all meta data shows correctly in the Sonos mobile app including album art.  If I send the URI only in play(), then I do not see a title, nor album art.   How do I send this favorite below into play() so that all meta data shows correctly?   

        {
            "id": "2/1",
            "parentID": "2",
            "title": "4 - Good Vibrations: The Beach Boys Channel",
            "artist": null,
            "album": null,
            "albumArtURI": "http://pri.art.prod.streaming.siriusxm.com/images/channel/20180518/9138-1-17-00-320x320.png",
            "uri": "x-sonosapi-hls:live%3a9138?sid=37&flags=8480&sn=2"
        }

**Comment by bencevans** [comment]
Hi @jpoeppelman1. Please checkout:

* [Generate Custom Metadata Documentation](https://github.com/bencevans/node-sonos/blob/29ce923a3f261d949d02973fba24835fa5ea8241/docs/helpers.md#sonoshelpersgeneratecustommetadatastreamuri-itemid-duration-title-artist-album-coverurl-parentid)
* https://github.com/bencevans/node-sonos/issues/330 'Question: Send custom metadata' - for examples
