### ISSUE TITLE
Idea: Promisified Version of device discovery

### ISSUE THREAD

**Issue by svrooij** [bencevans/node-sonos#419]

**Comment by bencevans** [comment]
I like the idea!

Maybe something along the lines of...

```
await sonos.discoverOne()
// Returns after first instance is found out times out

await sonos.discover({timeout: 2 * 1000})
// Returns an array of all that have announced within a sensible default
```

**Comment by ebaauw** [comment]
You only need a UPnP announcement from one zoneplayer.  When subscribing to `ZoneGroupTopology` events, you receive an event containing all zoneplayers in the household.  It also contains enough info to determine which zoneplayers are (stereo pair) slaves or (home theatre) satellites.  It does require recursively invoking the XML to javascript conversion.
