### ISSUE TITLE
Question: How can I add a "My Sonos" album, playlist to the queue

### ISSUE THREAD

**Issue by hklages** [bencevans/node-sonos#438]
Hi. 
With `getFavorites`, I get an sorted array of all "My Sonos" stations, albums, songs and playlist. That works fine. I am able to "activate" the stations either with `playTuneinRadio`  or `setAVTransportURI` for Amazon Prime stations. 

But how can I fill the queue with tracks from **playlists** in "My Sonos"?

Thanks for helping.

**Comment by bencevans** [comment]
Looking at the Python client there may be the ability to provide a file uri to the playlist such as:

```js
sonos.play('file:///jffs/settings/savedqueues.rsq#28')
```
> https://stackoverflow.com/questions/47611075/how-can-i-play-a-sonos-playlist-using-python-soco

I don't have access to my Sonos system at the moment. @svrooij may be able to shine some further light. Alternatively individually queue each song manually.

**Comment by svrooij** [comment]
What buttons would you press in the PC version of the sonos app if you do this? I'm not really sure what you want to accomplish.

If you have a script i'll be able to tell you the steps needed to do this with our library.

**Comment by hklages** [comment]
Hi, thanks. 
`sonos.play('file:///jffs/settings/savedqueues.rsq#28')` works fine for me.
