### ISSUE TITLE
setLEDState does not work

### ISSUE THREAD

**Issue by hklages** [bencevans/node-sonos#446]
I would like to `setLEDState('Off')` but it does not work. getLEDState works fine.
Instead of 'Off' I also tried On, on, off, 0, 1, true, false - all lead to error message.

## Current Behavior
I receive "Request failed with status code 500" and the stack.

## Sample code or executed example
```
sonosPlayer.setLEDState('Off') // On | Off
      .catch(error => { console.log('Error occurred %j', error); });
```

## Versions (and Environment)
**node-sonos version**:  1.12.4.
**Node-RED**: 1.02

**Comment by svrooij** [comment]
You're right there was a typ-o in the **DeviceProperties** service. Will be fixed soon.

**Comment by svrooij** [comment]
Solved with https://github.com/bencevans/node-sonos/pull/447/commits/6b491292392b6a19ec3a7ac7c8c8072222c50d20

**Comment by hklages** [comment]
Thanks a lot. Both issues are solved (this and the playmode). 
Great.

**Comment by svrooij** [comment]
Glad to help. [Check out how to sponsor me](https://github.com/sponsors/svrooij) :wink:
