### ISSUE TITLE
searchMusicLibrary -> Albums with ":" or "/" does not work

### ISSUE THREAD

**Issue by yoogie27** [bencevans/node-sonos#450]
I am using sonos-web and having issues with some albums. I tracked it down to albums having either ":" or "/" in the name. The backend code calls this.sonos.searchMusicLibrary("albums", "Series1 : Blabla", { start: 0, total: 100}, "/")

## Expected Behavior

Return album content

## Current Behavior

Empty result

## Versions (and Environment)

**Node version**: v8.12.0
**node-sonos version**: v0.19.0
**OS**: Mac / Linux

**Comment by yoogie27** [comment]
Potential solution: 
In lib/sonos.js, line 120, replace encodeURI with encodeURIComponent

**Comment by svrooij** [comment]
This got something to do with the fact that Sonos used these special characters as delimiter to mark levels when browsing the library

**Comment by yoogie27** [comment]
Will do after new year's eve
