### ISSUE TITLE
getSpotifyConnectInfo() does not work anymore

### ISSUE THREAD

**Issue by hklages** [bencevans/node-sonos#458]
getSpotifyConnectInfo and even the plain http code results in an error. 

## Current Behavior
request failed with status code 404

## Possible Solution
It seems that Sonos has removed some pages from the internal webserver recently. 

## Versions (and Environment)
current

**Comment by svrooij** [comment]
It seems like axios started parsing the response already.

If I change [these lines](https://github.com/bencevans/node-sonos/blob/934cf748243b7b4234c3150e1c171a9856838be6/lib/sonos.js#L948-L951) to:
```node
Sonos.prototype.getSpotifyConnectInfo = async function () {
  const uri = `http://${this.host}:${this.port}/spotifyzc?action=getInfo`
  return request(uri).then(response => response.data)
}
```

It just works again, I have Sonos version 10.6.1 by the way, not sure if that matters.
