### ISSUE TITLE
Invoking "Next" throws an error

### ISSUE THREAD

**Issue by jtmarmon** [bencevans/node-sonos#46]
`"Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Next"`

Everything else is working fine for me (pause, play, previous)

**Comment by iheart2code** [comment]
I am currently experiencing this issue. Is it fixed in another branch or something?

**Comment by iheart2code** [comment]
I think this is caused by including a Speed argument in the Next command.

See https://github.com/bencevans/node-sonos/blob/master/lib/sonos.js#L505
