### ISSUE TITLE
Two tests failing

### ISSUE THREAD

**Issue by svrooij** [bencevans/node-sonos#460]
Two tests are failing:

```plain
  1) Sonos - Device
       should getMusicLibrary("sonos_playlists"):
     AssertionError [ERR_ASSERTION]: should have items
      at /Users/stephan/Projects/node-sonos/test/sonos.test.js:563:7
      at processTicksAndRejections (internal/process/task_queues.js:94:5)

  2) Sonos - Device
       should getPlaylist():
     AssertionError [ERR_ASSERTION]: should have items
      at /Users/stephan/Projects/node-sonos/test/sonos.test.js:575:7
      at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

Not sure if it matters, can someone check it out if they can still use the `sonos.getMusicLibrary('sonos_playlists')` and `sonos.getPlaylist('1')` functions

## Possible Solution

Fix or remove the tests

## Sample code or executed example

1. `SONOS_HOST=192.168.x.x npm run test`

## Versions (and Environment)

**Node version**: 12.15.0
**node-sonos version**: latest master
**OS**: Mac

**Comment by hunter-hunter** [comment]
I'm trying to use this library for the first time and trying to get the playlists returned from the `getMusicLibrary()` function with no luck. Other functions like DeviceDiscovery and currentTrack work so I know the connection is being made to the speaker but no matter what I try I only receive `{"returned":"0","total":"0","updateID":"0"}` from `getMusicLibrary()`. Seems like it could be related to this issue.

**Comment by svrooij** [comment]
@hunter-hunter I closed the issue because two of the previous used tests stopped working.
If you are having issues with the library, it’s best to create a new issue.

We have a template configured to specify all the details about your environment.

**Comment by hunter-hunter** [comment]
Thank you. I created a new issue #487
