### ISSUE TITLE
Time jump feature

### ISSUE THREAD

**Issue by Schotsl** [bencevans/node-sonos#462]
I feel kinda stupid asking for this feature since I'm afraid I might just be missing it: but there doesn't appear to be a function that allows me to move in the track. I would think this is already supported since it seems like a pretty big feature.

I need it so I can go back to the beginning of a song. For now, I just go to the previous song and then the next to end up at the start again but I would like to make it possible to go to the middle of a song and I don't see how I would go about that using the current functions.

**Comment by Schotsl** [comment]
I just missed it indeed, turns out I'll have to use the `seek` function ;)

**Comment by iDavidB** [comment]
This function does exist! It's called "seek". You can find documentation for it [here](https://github.com/bencevans/node-sonos/blob/master/docs/sonos.md)

**Comment by Schotsl** [comment]
@iDavidB I knew I was missing something. Thank you very much! :)
