### ISSUE TITLE
Notification does not continue tracks being initiated by Spotify App

### ISSUE THREAD

**Issue by hklages** [bencevans/node-sonos#464]
Play notification does not restore the previous played song in case that song has been initiated by the Spotify app. The URI is: x-sonos-vli:RINCON_B8E93750C30801400:2,spotify:<a lot of digits and characters>

## Expected Behavior
Continue that "stream" after having played the notification.

## Current Behavior
After playing the notification the music stops - previous track is not being restored.

## Possible Solution
Be able to play a track with: 
media.CurrentURI
x-sonos-vli:RINCON_B8E93750C30801400:2,spotify:<xxx>
upnp class
object.item.audioItem.linein

<xxx> is the sequence of characters and digits - no idea what it stands for.

## Versions (and Environment)

**Node version**:  
**node-sonos version**: 1.13
**OS**: Windows 10

**Comment by svrooij** [comment]
I think even with the regular Sonos App, you cannot play something else and then return to a queue started from the Spotify app.

Once you switch the TransportUri (when switching to the internal queue or radio station or even the playbar tv input or play a separate mp3 in this case), the previous connection that was setup with spotify is lost forever. Music started from the spotify app just creates a personal temporary queue on the spotify server which your speaker will connect to.

The metadata from those songs also looks different

**Comment by hklages** [comment]
Thanks for clarification.
