### ISSUE TITLE
deviceDescription() property '_' - strange value

### ISSUE THREAD

**Issue by hklages** [bencevans/node-sonos#465]
deviceDescription() now returns asproperty '_' with strange content: 
"\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n  
  \n    \n    \n    \n    \n    #DEACTIVATION_STATE_TAG_AND_VALUE#\n    #DEACTIVATION_TTL_TAG_AND_VALUE#\n    #DEACTIVATION_DATE_TIME_TAG_AND_VALUE#\n    \n    \n    \n    \n  "

## Expected Behavior
no  property '_'

## Current Behavior
see above

## Possible Solution
delete that property

## Versions (and Environment)
**node-sonos version**: current

**Comment by svrooij** [comment]
The Sonos software seems to have a bug. The `http://192.168.2.4:1400/xml/device_description.xml` file seems incorrect. The used xml parser cannot handle it.

This issue isn’t solve able without changing the entire xml library, I’m tempted to close this issue since I don’t have a solution for this. 

```xml
<?xml version="1.0" encoding="utf-8" ?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>
  <device>
    <deviceType>urn:schemas-upnp-org:device:ZonePlayer:1</deviceType>
    <minCompatibleVersion>56.0-00000</minCompatibleVersion>
    <legacyCompatibleVersion>36.0-00000</legacyCompatibleVersion>
    <apiVersion>1.18.9</apiVersion>
    <minApiVersion>1.1.0</minApiVersion>
    <displayVersion>11.2</displayVersion>
    <extraVersion>OTP: 1.1.1(1-16-4-zp5s-0.5)</extraVersion>
    <roomName>Kantoor</roomName>
    <displayName>Play:5</displayName>
    <zoneType>5</zoneType>
    <feature1>0x02000002</feature1>
    <feature2>0x00006172</feature2>
    <feature3>0x0003102a</feature3>
    <seriesid>P100</seriesid>
    <variant>0</variant>
    <internalSpeakerSize>3</internalSpeakerSize>
    <bassExtension>0.000</bassExtension>
    <satGainOffset>0.000</satGainOffset>
    <memory>32</memory>
    <flash>32</flash>
    #DEACTIVATION_STATE_TAG_AND_VALUE#
    #DEACTIVATION_TTL_TAG_AND_VALUE#
    #DEACTIVATION_DATE_TIME_TAG_AND_VALUE#
    <flashRepartitioned>1</flashRepartitioned>
    <ampOnTime>425</ampOnTime>
    <retailMode>0</retailMode>
  </device>
</root>
```

**Comment by pascalopitz** [comment]
What about replacing the strings with some nodes, before handing it to the
XML parser?

**Comment by svrooij** [comment]
I think it would then be best to use a regular expression to remove #...# with letters and underscores in between. And maybe make it optional.

We welcome every contribution, so if you want to give it a go.

Looking forward to see your PR.

**Comment by pascalopitz** [comment]
I made the tags into comments ... that shouldn't throw the xml parser

**Comment by svrooij** [comment]
Once this build completes a new version will be online https://travis-ci.org/github/bencevans/node-sonos/builds/703139452
