### ISSUE TITLE
Is there any way to bypass the added buffer while playing a mp3 stream?

### ISSUE THREAD

**Issue by filahf** [bencevans/node-sonos#467]
## Expected Behavior
I would like to play content from radio stations in, as close to, real time as possible.

## Current Behavior
It seems like Sonos adds a buffer (roughly 7 seconds of data) while playing a radio stream. The same radio stream played in e.g VLC will have a buffer with roughly 1 second delay.

**Comment by svrooij** [comment]
Does your Sonos respond differently if you start a radio station with this library (compared to the Sonos app)? I think this is an issue with Sonos buffering, that doesn't have anything to do with this library.

If you think this analysis is incorrect, please re-open this issue so we can investigate.
