### ISSUE TITLE
Add Allcontributors

### ISSUE THREAD

**Issue by svrooij** [bencevans/node-sonos#470]
@bencevans are you ok with adding [All Contributors](https://allcontributors.org/) to this library?

It will add somthing like [this](https://github.com/svrooij/sonos2mqtt#contributors-) to the readme, so all contributors actually get displayed in the readme. So even though this is your library all other people who contributed also have their image added to the readme (automatically.)

If you're ok with it, I'll create a inital PR, but you (as owner) have to autorize the bot (I think).

**Comment by bencevans** [comment]
Yes. Very happy for this to be added!
