### ISSUE TITLE
Should we setup 'beta' release from new beta branch?

### ISSUE THREAD

**Issue by svrooij** [bencevans/node-sonos#478]
## Should we have a beta branch with a beta release?

A lot of libraries have a special branch setup do to small **beta** releases that get pulled to **master** once in a while. Do you think **node-sonos** should also implement that strategy?

- By having a **beta** release we can test PR's more easily, by just releasing something to beta, and have people test it out. Beta suggest that things might break when using the beta release.
- By having a **beta** release it should be easier to release big changes. This library doesn't have a high test coverage, so having a beta would allow other contributors to get their changes merged quicker.

## Votes

- 👍 For Yeah, you should!!
- 😕 For, I don't know, need more info
- 👎 For no, why would you need that

Also comment your thoughts please.

Related to:
- https://github.com/bencevans/node-sonos/pull/472#issuecomment-654661054

**Comment by pascalopitz** [comment]
I think we could spend some time working on the test coverage. Right now there's like one big file, and it looks like it'd be pretty hard to make changes in there. Could we maybe break the tests up? I'd suggest a convention of tests stored close to the relevant files, i.e. in `__test__` folders. Personal choice would be switching to jest?

**Comment by svrooij** [comment]
This poll wasn't about test coverage, but you're right about the test part.

> I think we could spend some time working on the test coverage. Right now there's like one big file, and it looks like it'd be pretty hard to make changes in there. Could we maybe break the tests up? I'd suggest a convention of tests stored close to the relevant files, i.e. in `__test__` folders. Personal choice would be switching to jest?

- Folder, no opinion, I'll follow
- Jest, yes please.  In [my other sonos library](https://github.com/svrooij/node-sonos-ts) I've also switched to Jest, I really like the build-in code coverage check that you can see if you open **Run tests** [here](https://github.com/svrooij/node-sonos-ts/runs/822023910?check_suite_focus=true).
- Jest also allows easy integration with [coveralls](https://coveralls.io/github/svrooij/node-sonos-ts?branch=master) to check which parts of the code are checked.
- Using jest would probably allow us to copy [these tests](https://github.com/svrooij/node-sonos-ts/tree/master/tests), since they will both test the same code being executed.

**Comment by pascalopitz** [comment]
> This poll wasn't about test coverage

This was meant as a comment to your original point:

> This library doesn't have a high test coverage, so having a beta would allow other contributors to get their changes merged quicker.

I'm all for a beta branch. But if contributions are not happening because of lack of test coverage, I'd be willing to put in some work to increase that also. That's all.

**Comment by svrooij** [comment]
I've created a `alpha` branch but the NPM_TOKEN still has to be setup see #480

**Comment by svrooij** [comment]
Since @bencevans added the NPM secret we can now release much faster.
Choose for auto releases from the alpha branch for now, and then once in a while we push all the changes from alpha to master.

The alpha release might break sometime!!
