### ISSUE TITLE
Setup NPM_TOKEN in secrets

### ISSUE THREAD

**Issue by svrooij** [bencevans/node-sonos#480]
Hi @bencevans 

I've setup a new `alpha` branch.
It has a **release** workflow in it [workflow part](https://github.com/bencevans/node-sonos/blob/alpha/.github/workflows/run-tests.yml#L26-L55). That will trigger only on the alpha branch right now, see comment in workflow.

To release this `pre-release` version is needs an `NPM_TOKEN` as secret, could you set that up? 
[Semantic-release action](https://github.com/marketplace/actions/action-for-semantic-release#branches) is by default setup to create a pre-release version of the branches `alpha` and `beta`.

1. Create a token at NPM
2. Go to [secrets](https://github.com/bencevans/node-sonos/settings/secrets) and create a new secret with `NPM_TOKEN` as name.

## Replace travis?

Recently I've switched all other projects to Github actions for testing and releasing, because it feels so much faster, and I don't like the wait. Also it's very much integrated into the github UI. This "alpha" release can be to test out the new release flow and maybe we can switch over some day.

**Comment by bencevans** [comment]
Hi @svrooij 

I've setup an NPM_TOKEN. Yes, I've had a play with actions too and been pretty impressed. I'd be happy to move over.

**Comment by svrooij** [comment]
We released the first alpha lastnight with the new action, so it seems to be working.
