### ISSUE TITLE
getMusicLibrary returns nothing

### ISSUE THREAD

**Issue by hunter-hunter** [bencevans/node-sonos#487]
Calls to `getMusicLibrary()` return 0 items regardless of the search type (playlist, artists, sonos_playlists, etc.) I've verified through node-red-contrib-sonos-plus that there are playlists available from the speaker(s) in my setup. Other function calls like `currentTrack()` work correctly when using the same IP address.

## Expected Behavior
Should return the list of playlists, artists, etc. available for the speaker.

## Current Behavior
No search that I've tried has returned any results.

## Sample code or executed example

```
const Sonos = require('sonos').Sonos
const sonos = new Sonos('172.16.4.129')

sonos.getMusicLibrary('sonos_playlists', { start: 0, total: 25 }).then(playlists => {
  console.log('Got current sonos playlists %j', playlists)
}).catch(err => { console.log('Error occurred %j', err) })
```

## Versions (and Environment)

**Node version**: 12.17.0 
**node-sonos version**: 1.14.0
**OS**: MacOS

**Comment by svrooij** [comment]
I've tried this locally, and at my PC it just works.
Do you have VSCode?

Can you checkout the repository, add a `.vscode/launch.json` file with the following content:
```jsonc
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch current example",
      "program": "${file}",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "env": {
        "DEBUG":"sonos:*",
        "SONOS_HOST":"192.168.x.x" // Replace this with your SONOS IP
      },
    }
  ]
}
```

Then navigate to `examples/getplaylists.js` and press `F5`. This will launch the debugger. You can even set [breakpoints](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_breakpoints) to see exactly what is going on.

**Comment by hunter-hunter** [comment]
Thank you for the help! 

It seems that the issue I was having was not using the correct function for the information I was after.`getplaylists.js` returns 0 results for me, however `getsonosfavorties.js` and `getsonosplaylists.js` do give me the information I was expecting. Do you happen to know where in the Sonos app I can find the playlists that `getMusicLibrary()` is supposed to return?

**Comment by svrooij** [comment]
No I have no idea where you can find those. Maybe one is the playlists you have on your nas (local library). Personally I only use Spotify playlists.

**Comment by hklages** [comment]
They are named "imported playlists".  In the Sonos App, use tab "Browse", select Music Library, select imported playlists. 
You can add them to My Sonos (in total with new swim lane imported playlist) or playlist by playlist and then they show up in the swim lane playlists.

**Comment by hunter-hunter** [comment]
Great! Thank you!
