### ISSUE TITLE
Discussion: regenerating services

### ISSUE THREAD

**Issue by svrooij** [bencevans/node-sonos#489]
Recently I’ve started a new repository that tries to [document](https://svrooij.io/sonos-api-docs) all the available Sonos services.

It combines all the available services (from service discovery) with a [documentation file](https://github.com/svrooij/sonos-api-docs/blob/main/docs/documentation.json). PR greatly appreciated. 😉 

Questions:
- would you guys be interested in a a auto-generated version of all the services? In order for all the Sonos actions to be available in this library.
- anybody who wants to give it a go? Check the [generator](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs) and the [documentation template](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs/templates/docs) to get started.

This issue is just to see if others are interested in this. I’m more then happy to get you guys started, but I’m not in the position to finish this transformation myself (limited time available).

**Comment by hklages** [comment]
Great idea. I am glad to bring in my knowledge. 
- In a first step I will add more links pointing to other sources
- I use a SONOS beam and a Play: 3 (and Play:5, Play:1) - will add that
- explored some action in more detail - will add them in documentation

Thanks for bringing that all together!

**Comment by svrooij** [comment]
@hklages you can check out my initial version of the generated services. I deliberately picked a different naming scheme, so the new services don’t override the existing services.

These services aren’t used in the library, but using these services next to the current services should be an option.

If you want to extend the documentation, you can send a PR for the documentation.json file in the docs library.

**Comment by hklages** [comment]
yes - found the documentation.json already. 
... and the project.json file in _data  for additional internet sources.
