### ISSUE TITLE
Update axios to  >=0.21.1

### ISSUE THREAD

**Issue by htilly** [bencevans/node-sonos#503]
npm audit gives me:

High          │ Server-Side Request Forgery
Package       │ axios    
Patched in    │ >=0.21.1 
Dependency of │ sonos    
Path          │ sonos > axios
More info     │ https://npmjs.com/advisories/1594

**Comment by htilly** [comment]
Guess this relates to:
https://github.com/bencevans/node-sonos/pull/501

**Comment by bencevans** [comment]
Thanks for the report, fixed by #501
