### ISSUE TITLE
Event for when groups change?

### ISSUE THREAD

**Issue by realwakils** [bencevans/node-sonos#511]
I would like to know how I can know when the groups change? For example when I change one of my devices into another group.

I tried with ZoneTopology but the event was never called

**Node version**:  v14.15.2
**node-sonos version**:  the latest
**OS**:  windows 10

**Comment by pascalopitz** [comment]
```
import { Listener } from 'sonos';

Listener.on('ZonesChanged', (...args) =>{});
```
