### ISSUE TITLE
1.0.0 Release [$15]

### ISSUE THREAD

**Issue by stephen** [bencevans/node-sonos#54]
- [x] Logical Devices (PR: https://github.com/bencevans/node-sonos/pull/53)
- [x] Logical Device Search / Management (PR: https://github.com/bencevans/node-sonos/pull/55)
  - When dealing with logical devices, perhaps it makes sense for us to go one level better and also concern ourselves with topology changes, i.e. a `Manager` class that will emit events for grouping changes / devices connecting, disconnecting, etc. Would make client code much easier to deal with out of the box.
- [x] Group support for `getLEDState`/`setLEDState`
- [x] ~~Changes to `Sonos` class to use cached volume (`getVolume()`)~~
- [ ] Documentation changes
  - [ ] Notes about `initialize()` semantics (breaking change from 0.x -> 1.0)
  - [ ] Notes on LogicalDevice usage
##

**Comment by MartinAyla** [comment]
Thanks for all the work on this. I just donated $15.

Actually I wanted to donate (bounty) to AirSonos - but I guess node-sonos is part of that? :)

Also, does the logical groups work in AirSonos now, meaning, can I AirPlay to ie. two Sonos devices at the same time with the latest relase?

**Comment by stephen** [comment]
(Perhaps this should be in an [airsonos issue](https://github.com/stephen/airsonos/issues)..)

@MartinAyla - you should already be able to play to two sonos devices at the same time with airsonos, provided that they're grouped in the Sonos controller. You should connect to the "primary" device in the group.

After these changes (and changes in airsonos) merge, group playback will be less clunky, meaning you will only see the "primary" instance as an option, and nice things like group volume adjustment will be supported.

**Comment by svrooij** [comment]
@stephen what would you still like to change for us to go forward in calling node-sonos version 1.0.0

At the moment I implemented leave/join group commands. That way you can just join one device to the group and it will figure out itself which player it should join.

Since the last activity was almost 3 years ago, I’ll be closing this issue. Feel free to open it again if still think we should implement logicalDevice search.
