### ISSUE TITLE
Not returning URL for track?

### ISSUE THREAD

**Issue by djMax** [bencevans/node-sonos#60]
Just getting started with latest node-sonos after a long time away. When getting the current track info, I see that it doesn't seem to parse the actual URL for the content. Isn't this necessary for being able to turn around and play that track later? If so that seems like something that should get parsed in parseDIDL or somewhere. I can make the changes if I'm understanding this correctly.
##

**Comment by bencevans** [comment]
Yep! This would be a good change to make. Feel free to open a pull-request else hopefully myself or someone else will be able to do this in the future.

**Comment by djMax** [comment]
It's a bit odd - sometimes the URL comes back and sometimes it doesn't. Haven't figured out the rhyme or reason behind it yet. Once I do I'll send a PR.
