### ISSUE TITLE
Decouple listener from server

### ISSUE THREAD

**Issue by monsur** [bencevans/node-sonos#65]
Right now, listener.js creates a new server to listen for Sonos notifications. But there may be cases where a developer has an existing server where they'd like to receive notifications. For these cases, it might be nice to return a Connect middleware handler function which they can then plug into their own server.

**Comment by bencevans** [comment]
+1

**Comment by bencevans** [comment]
In review I don't think very many users need this option. If you're looking to listen on specific ports checkout @driskell's work on https://github.com/bencevans/node-sonos/pull/135 and https://github.com/bencevans/node-sonos/pull/137
