### ISSUE TITLE
Stuck Searching for Sonos devices on network...

### ISSUE THREAD

**Issue by ktec** [bencevans/node-sonos#73]
So I started by trying to use the airsonos app, but it just gets stuck at

```
Searching for Sonos devices on network...
```

I've documented it more closely here https://github.com/stephen/airsonos/issues/135 I've not had any success finding anyone who can help guide me through debugging but it was suggested that someone here may know enough to help.

To summarise, I've got these installed:

```
sudo n 0.10.36
sudo npm install -g airsonos
sudo n 0.12.0
n use 0.10.36 /usr/local/bin/airsonos
```

Airsonos project uses this projects `sonos.LogicalDevice.search` feature to locate devices on the network, and its this bit thats not working for me. I really don't know anything about node.js so I'm poking around in the dark here, but so far I've:

- ensured that I'm not running a firewall
- i have great connection with the sonos device
- the sonos app can actually find and control the device

I'm not sure what to do to make any progress with this, but I'm really keen to be able to send music to my Sonos speaker without using the main app. I've just installed `node-inspector` and I'm trying to debug and step through the code but I'm really not sure what I'm looking for.

Any help would be great thanks...

**Comment by bencevans** [comment]
Thanks for the report @ktec.

What Sonos devices have you got on your network that you're trying to find?

**Comment by ktec** [comment]
Hi Ben, its the PLAY:1

I was debugging through the code for hours last night but I'm no good at javascript debugging so i didn't really get anywhere....was only able to stop the code before it defined the Search() class, but I couldn't get it to stop inside the searching call

**Comment by jweinstein** [comment]
Same issue, I have a Soundbar and a PLAY:1

**Comment by HarlekinX** [comment]
Mmmh, I have 2x PLAY:1 and 1x Sub and no problem to discover them (in less then 2 seconds).

Where do you run the script. Is it a physical machine, has it multiple network adapters, is i a virtual machine and is bridged networking active?

**Comment by jweinstein** [comment]
Regular Mac OS X machine on the same network. Nothing fancy. :(

**Comment by ktec** [comment]
Me too, regular mac book air, nothing fancy, and the Sonos app seems to
locate the device without trouble. Can you suggest how/where I can drop
debug in to actually step through the discovery thing and I can probably
help resolve this.

On 30 March 2015 at 18:31, Jeff Weinstein <notifications@github.com> wrote:

> Regular Mac OS X machine on the same network. Nothing fancy. :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bencevans/node-sonos/issues/73#issuecomment-87762973>.
>



-- 
keithsalisbury@gmail.com

**Comment by bencevans** [comment]
@ktec @jweinstein: are you both using the airsonos module?

I'm able to discover devices on a linux box running node@v0.10.36 and the node-sonos@master

Best way to debug this is to use Wireshark and check the broadcast packet is actually being sent and whether any Sonos devices are sending anything back.

**Comment by jweinstein** [comment]
Would it be possible to set up a time to screen share with you to walk
through that?

**Comment by ktec** [comment]
Hey Ben, Yup I'm using the airsonos module, I'll give it a whirl with wire
shark, you wouldn't happen to have a packet filter that will help zero in
on the relevant packets?

On Tuesday, March 31, 2015, Ben Evans <notifications@github.com> wrote:

> @ktec <https://github.com/ktec> @jweinstein
> <https://github.com/jweinstein>: are you both using the airsonos module?
>
> I'm able to discover devices on a linux box running node@v0.10.36 and the
> node-sonos@master
>
> Best way to debug this is to use Wireshark and check the broadcast packet
> is actually being sent and whether any Sonos devices are sending anything
> back.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bencevans/node-sonos/issues/73#issuecomment-87889384>.
>


-- 
keithsalisbury@gmail.com

**Comment by bencevans** [comment]
I'm afraid it's a busy week, ping me Friday and I might be able to help.

Else If you're able to do a [packet capture](http://www.howtogeek.com/104278/how-to-use-wireshark-to-capture-filter-and-inspect-packets/) in Wireshark and send it to me (assuming you're comfortable sharing your net packets!) and run maybe with screen recording the node-sonos program/code.

**Comment by bencevans** [comment]
@ktec Cheers! I'll see what I can come up with...

**Comment by bencevans** [comment]
@ktec just `http` should get rid of the noise so long as you haven't got loads of other requests being made by fb etc.

**Comment by ktec** [comment]
Thanks mate I'll do a snoop and let you know what I come up with

On Tuesday, March 31, 2015, Ben Evans <notifications@github.com> wrote:

> @ktec <https://github.com/ktec> just http should get rid of the noise so
> long as you haven't got loads of other requests being made by fb etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bencevans/node-sonos/issues/73#issuecomment-87891107>.
>


-- 
keithsalisbury@gmail.com

**Comment by bencevans** [comment]
@ktec
![Ta](http://media.giphy.com/media/Zw3oBUuOlDJ3W/giphy.gif)

**Comment by hypascend** [comment]
I hit the exact same issue today and I have a workaround/fix.  It would need someone with more knowledge of how it all works to figure out why it works in some environments and not in others.  My basic understanding is that the default broadcast that is used to search for Sonos devices fails.  I have a theory that it might be due to the broadcast address being invalid.

Anyway if you located the following in the sonos.js file:

  this.socket.bind(function() {
    _this.socket.setBroadcast(true);
    _this.socket.send(PLAYER_SEARCH, 0, PLAYER_SEARCH.length, 1900, **'239.255.255.250'**);
  });

and replace it with the broadcast address for your network, in my case it was 192.168.0.255, therefore it looks like:

  this.socket.bind(function() {
    _this.socket.setBroadcast(true);
    _this.socket.send(PLAYER_SEARCH, 0, PLAYER_SEARCH.length, 1900, **"192.168.0.255"**);
  });

**Comment by ktec** [comment]
Sorry I didn't finish up with this, I went off on holiday and my laptop died. Thanks for Sharing your solution @hypascend I'll give it a try when I get my laptop back.

**Comment by ktec** [comment]
Works perfectly, thanks for sharing :bow:

**Comment by hypascend** [comment]
You are welcome. :)

**Comment by bencevans** [comment]
Thanks for sharing! I'm not sure why we broadcast on that address to be
honest. It was probably just what the Sonos Controller was doing back when
this was written.

Maybe we could broadcast on both.

**Comment by hypascend** [comment]
239.255.255.250 is the Simple Service Discovery (SSDP) multicast address.  I suppose the question is, why are we trying to broadcast to a multicast address.  I think it might be worth doing some analysis on the setup of the broadcast socket as . 

It could be that some networks/OS don't allow a broadcast to a multicast address and that is why we are seeing it only affect some people.  I think your idea works, to cover both scenarios, but maybe we don't need the SSDP part anymore?

If I get time I will do some packet analysis on when it does the current broadcast compared to the subnet specific broadcast.

**Comment by joeMJ** [comment]
Still have this in actual ubuntu trusty. Editing the sonos.js to match my local broadcast did not fix it. Machine is a vm within a qnap (maybe that bridging to local network has an issue, but anything else works flawless on that box). I'd love to have a config file to enter my 5 devices ip manually and skip search... this would help a lot.

**Comment by bencevans** [comment]
@joeMJ you're able to create instances of the Sonos "class" without using the search interface. Check out https://github.com/bencevans/node-sonos/blob/master/examples/next.js for an example.

**Comment by gers1978** [comment]
Changing the broadcast address to 192.168.1.255 in songs.js worked for me (my router address is 192.168.1.254)

I had to use:

[code]sudo nano sonos.jsp[/code]

to edit it though

**Comment by r1k** [comment]
I've been having a similar issue trying to run airsonos from an Ubuntu 15.04 box on my network - no sonos devices listed.  However it is working on my RaspberryPi 2 both running node 0.10.33.
After getting it working on the Raspberry Pi I was trying to getting it working in a docker image on my Ubuntu box without any joy, so I finally resorted to installing it natively to the Ubuntu box and still no luck.

However reading the comments above about 239.255.255.250 (SSDP) and it seems that by default Ubuntu doesn't set up the correct routing for multicast traffic, after adding the route 224.0.0.0/4 to the eth0 interface everything sprung in to life.

**Comment by YellowLemon1** [comment]
I had this same problem. Changing the broadcast address did not work. The solution: remove my 'Sonos Bridge' from the Sonos system, and either: connect ethernet directly to a speaker, or use standard WiFi setup with the Sonos. I went with the latter as Sonos themselves have now deprecated the Bridge device. The Bridge must be blocking/dropping the broadcasts from getting onto the SONOS-NET where the speakers are (?). I didn't check this with wireshark though, so I might be wrong.

**Comment by bencevans** [comment]
Unfortunately I can't test this as have always just used the standard WiFi
setup with the devices I've got :/

**Comment by YellowLemon1** [comment]
It doesn't matter, the problem is a non-issue because using a SONOS Bridge is now unnecessary for most people. I'm just commenting here to document my experience/make others aware. Cheers.

**Comment by bencevans** [comment]
Awesome, cheers :)

**Comment by datadl** [comment]
Worked like a charm!!!!!!!!! Thanks so much :+1:

**Comment by chamat** [comment]
Hi I am a newbie, and I am wondering how do i locate the sonos.js file???

I followed the instructions for the installation but it gets stuck @ searching for sonos devices on network

Thanks

**Comment by vincentpalita** [comment]
Hi @chamat,

if you are on a mac: /usr/local/lib/node_modules/airsonos

Cheers,
Vincent

**Comment by bencevans** [comment]
@chamat If you've installed the module locally in your project and then it's found at `node_modules/sonos/sonos.js`.

**Comment by bencevans** [comment]
@gers1978 suggestion has worked for me. Shall try and find a way of picking that network automatically in the library else maybe broadcast on all networks

**Comment by bencevans** [comment]
I've started #101 to see if there's a way of fixing this within the project so that it can work out of the box. Reviews are much appreciated! :)

**Comment by bencevans** [comment]
https://github.com/bencevans/node-sonos/issues/73#issuecomment-139685145

**Comment by gmon3y** [comment]
I used Docker to get it all installed on my NAS drive and it installs just fine but seems to hang at searching for devices, similarly to the issues others in here had/have. I adjusted the sonos.js file to reflect that of my subnets broadcast address and it resulted in the same issue. I also confirmed that multicast works just fine on my network.

Does anyone have suggestions? Any help appreciated!

**Comment by bencevans** [comment]
Hi @gmon3y 

Have you had any more luck so far?

Else please can you supply example code, dockerfile, node-sonos version.

Is this from AirSonos or using node-sonos directly? If AirSonos, browsing the AirSonos's issues may be handy... https://github.com/stephen/airsonos/issues/30

Cheers,

Ben

**Comment by gmon3y** [comment]
Hey @bencevans 

Thank you for the reply. It is the AirSonos I am using currently. I pulled the docker from: leachbj/airsonos by using the following command: 'docker run -d --restart=always --net="host" --name="airsonos" -p 5000-5050:5000-5050/tcp leachbj/airsonos'

When I performed the AirSonos diag, it displayed version 0.10.40 for Node-sonos but it too hung at the searching for devices stage.

Below is what the docker log shows:

*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 13
ok: run: avahi: (pid 23) 0s
ok: run: dbus: (pid 22) 0s

Searching for Sonos devices on network...

**Comment by bencevans** [comment]
Is there some sort of VPN or funky network management on your NAS?

I'm running this on an Ubuntu 15.10 host with Docker and an OpenVPN VPN...

**Connected to VPN**... No devices found by Docker container.

```
$ docker run --restart=always --net="host" --name="airsonos" -p 5000-5050:5000-5050/tcp leachbj/airsonos 
Unable to find image 'leachbj/airsonos:latest' locally
latest: Pulling from leachbj/airsonos
a3ed95caeb02: Pull complete 
5e160ca0bb5a: Pull complete 
1bed58d8a97f: Pull complete 
892d417c2fd9: Pull complete 
b978d18d9f6d: Pull complete 
349ecc2ac62f: Pull complete 
6148d15ea50f: Pull complete 
29a82edd40fb: Pull complete 
602016238152: Pull complete 
Digest: sha256:96a2e7f2570a78f388c8cbb97de87d898337e3adb634c54dca8e7017f4a9b70e
Status: Downloaded newer image for leachbj/airsonos:latest
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
No SSH host key available. Generating one...
Creating SSH2 RSA key; this may take some time ...
Creating SSH2 DSA key; this may take some time ...
Creating SSH2 ECDSA key; this may take some time ...
*** Running /etc/my_init.d/10_dbus.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 81
ok: run: dbus: (pid 91) 0s
ok: run: avahi: (pid 90) 0s
Searching for Sonos devices on network...
```
Nothing happens for a minute... [Ctrl-C]
```
*** Shutting down runit daemon (PID 81)...
*** Killing all processes...
```

**Disconnects from VPN** - AirSonos discovers the Sonos device on network within a few seconds

```
$ docker run --rm --net="host" --name="airsonos" -p 5000-5050:5000-5050/tcp leachbj/airsonos
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
No SSH host key available. Generating one...
Creating SSH2 RSA key; this may take some time ...
Creating SSH2 DSA key; this may take some time ...
Creating SSH2 ECDSA key; this may take some time ...
*** Running /etc/my_init.d/10_dbus.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 81
ok: run: dbus: (pid 88) 0s
ok: run: avahi: (pid 89) 0s
Searching for Sonos devices on network...

Living Room (@ 192.168.1.10:1400, RINCON_000E585B7C9801400:1)

Search complete. Set up 1 device tunnel.
```

**Comment by gmon3y** [comment]
@bencevans that is interesting. I did read some where that they had a similar issue and it turned out to be some VPN functionality. I did have VPN server set up on the nas itself. I disabled them but never actually removed/reinstalled after disabling the VPN. Just disabled VPN and restarted the container. I will give that a shot when I get home.

Thanks,
Jorge

**Comment by swissjon** [comment]
@gmon3y did you ever solve your issue? I'm having same problem.
