### ISSUE TITLE
Codacy code review parameters

### ISSUE THREAD

**Issue by HarlekinX** [bencevans/node-sonos#77]
I'm using JSHint and your `.jshintrc` configuration to verify my code. My pull requests got successfully verified by Travis CI. After about 24 hours I saw that my code failed.
The failed verification comes from Codacy.

1. failure : A variable was not camel case.
Even I have to agree my fault and corrected it, looking at `.jshintrc` I see ` "camelcase": false,`. The JSHint documentation says that camelcase checking is even deprecated and to use something like JSCS (which I could, but requires a config file)

2. failure: Not using curly braces in a one liner if statement.

So, how could it be avoided that a pull request needs to be corrected afterwards? My IDE can enable JSLint, JSHint, Closure Linter, JSCS and ESLint.
JSCS and ESLint allow config files like the `.jshintrc`

**Comment by bencevans** [comment]
Don't worry about the code style atm. I plan to use [standard](https://github.com/feross/standard)
