### ISSUE TITLE
TTS save/restore state

### ISSUE THREAD

**Issue by jaumard** [bencevans/node-sonos#83]
Hi,

If sonos is playing and I want to use TTS, music is stop -> tts is playing -> and it doesn't restart current song/playlist ... How I can implement this ?
##

**Comment by bencevans** [comment]
From what I think I remember (it's been a while), Sonos does keep the
playlist when the mode is switched.

So by finding a way yo change back to the playlist mode rather than radio
stream/TTS stream. Then send a play command.

Sorry I can't be anymore specific. Please keep us posted as to your
findings!

**Comment by jishi** [comment]
Late answer, but to restore a queue on a player, you need to set the AVTransportURI to the following:

x-rincon-queue:[UUID of player]#0

This can be set by queueNext() or play() in this API if I interpret the code correctly.

**Comment by jaumard** [comment]
Thanks! But I don't understand where I can have the UUID of player ? It's the name of the room ? 
And if I want to restore the TV instead of a queue it's the same ?

**Comment by jishi** [comment]
the UUID is usually UUID_ followed by the MAC address of the main interface, followed by 01400. I haven't used this library, but I'm sure it is available somehow.

If you by TV mean the line-in, it is instead x-rincon-stream:[UUID of player]#0

if you are talking about the spdif on the playbar, it is a bit different. I think it needs to be prefixed by "x-sonos-htastream" instead.

**Comment by kyvinh** [comment]
What I did was add the `TrackURI` metadata to the track object returned by `currentTrack()` like this: (note the usage of `data[0].TrackURI[0]`)

```javascript
/**
 * Get Current Track
 * @param  {Function} callback (err, track)
 */
Sonos.prototype.currentTrack = function (callback) {
  debug('Sonos.currentTrack(' + ((callback) ? 'callback' : '') + ')')
  var self = this
  var action = '"urn:schemas-upnp-org:service:AVTransport:1#GetPositionInfo"'
  var body = '<u:GetPositionInfo xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><InstanceID>0</InstanceID><Channel>Master</Channel></u:GetPositionInfo>'
  var responseTag = 'u:GetPositionInfoResponse'
  return this.request(this.options.endpoints.transport, action, body, responseTag, function (err, data) {
    if (err) return callback(err)
    if ((!util.isArray(data)) || (data.length < 1)) return {}
    var metadata = data[0].TrackMetaData
    var position = (parseInt(data[0].RelTime[0].split(':')[0], 10) * 60 * 60) +
      (parseInt(data[0].RelTime[0].split(':')[1], 10) * 60) +
      parseInt(data[0].RelTime[0].split(':')[2], 10)
    var duration = (parseInt(data[0].TrackDuration[0].split(':')[0], 10) * 60 * 60) +
      (parseInt(data[0].TrackDuration[0].split(':')[1], 10) * 60) +
      parseInt(data[0].TrackDuration[0].split(':')[2], 10)
    var trackUri = data[0].TrackURI[0];
    if ((metadata) && (metadata[0].length > 0) && metadata[0] !== 'NOT_IMPLEMENTED') {
      return (new xml2js.Parser()).parseString(metadata, function (err, data) {
        if (err) {
          return callback(err, data)
        }
        var track = self.parseDIDL(data)
        track.position = position
        track.duration = duration
        track.trackUri = trackUri
        track.albumArtURL = !track.albumArtURI ? null
          : (track.albumArtURI.indexOf('http') !== -1) ? track.albumArtURI
            : 'http://' + self.host + ':' + self.port + track.albumArtURI
        return callback(null, track)
      })
    } else {
      var track = { position: position, duration: duration }
      if (data[0].TrackURI) track.uri = data[0].TrackURI[0]
      return callback(null, track)
    }
  })
}
```

This `TrackURI` looks like `http://192.168.0.135:8282/test.mp3` (for my notifications) or `x-sonos-spotify:spotify%3atrack%3a2QfNZWOVYeycSM2bmrpm9W?sid=9&flags=8224&sn=1` (for Spotify) or `x-rincon-mp3radio://ice14.infomaniak.ch:80/lapremiere.mp3` (for web radio). There might be other types of `TrackURI` though like line-in, etc. Then I just check for `spotify` or `radio` to know whether to resume the radio or the queue like:

```javascript
    if (previousTrack.trackUri.indexOf("mp3radio") > -1) {
      console.log("Resuming radio")
      sonos.play(previousTrack.trackUri, callback);
    } else {
      console.log("Resuming queue")
      sonos.selectQueue(function() {
        sonos.play(callback);
      });
    }
```

I have yet to learn how to do branching/pull requests correctly so tell me if this is acceptable code to be included and I'll test this pull request thingie ;)

**Comment by svrooij** [comment]
I'm going to try out this code, and make a pull request for it (if it works).
The only change you made is implementing the ``trackUri`` in the ``currentTrack`` call right?

**Comment by kyvinh** [comment]
Yes, that's all. There are edge cases where it is neither a radio nor a queue that was previously playing but I don't remember. I don't use sonos anymore...
