### ISSUE TITLE
Find master sonos

### ISSUE THREAD

**Issue by VanCoding** [bencevans/node-sonos#84]
Hi bencevans!

Thank you for this useful library :)

When I group some sonos devices together, one of them is the master. I actually can see in the android sonos app, which one is the master and what devices are his slaves.

Is there a way to get that information with your library?

The problem I currently have is the following: I want to programmatically play a track on all devices. But when I do if for every device, the groups get ripped apart and I have to recreate the groups every time. I though I'll be able to avoid this by just playing the track on the master, since his slaves will then automatically play the track.

Any idea?

Thank you :)

**Comment by bencevans** [comment]
Hi Patrik,

You're very welcome :)

You should be able to get the master device in a zone by using getTopology
then when sending commands for the zone, send them to the master device and
the others should follow.

It might be worth checking out the code in this repo as there are some
helpers that might help communicate with the UPnP services.

Keep us posted as to how you get on!

Cheers,

Ben

**Comment by ryanjohnstone** [comment]
I can get the master device using topology but can't see how I would send a command to it. Would I have to parse out the IP address from location and use that to create a new Sonos object to call the commands with?

**Comment by bencevans** [comment]
Sounds like you've got it sussed there! We'd like to use zones as default
in the future rather than addressing logical devices however time is a bit
stretched at the moment. You're very welcome to check out the 1.x branch
where @stephen has been hard at work towards it however it's to be
considered unstable and a work in progress!

**Comment by bencevans** [comment]
As for the addSpotify issue, that does seem odd as looking at the code it should be queued as the next song (which I'm not actually happy with, instead it should be added to the end from that naming convention)... https://github.com/bencevans/node-sonos/blob/ca2c9870762ad0932e1bcc0fb0ae5818631f0753/lib/sonos.js#L518-L534

Please could you let us know what version of node-sonos you're using so we can look into it?

Cheers,

Ben

**Comment by ryanjohnstone** [comment]
Using version 0.8.0 but just realised in my actual project I'm using your lib from an npm package, specifying version 0.8.0 and the addSpotify method is missing from sonos.js. Not sure why that would be? Does the npm module need updating or something?

**Comment by bencevans** [comment]
Fraid publishing has been a bit lax recently due to other workload. I've just published v0.9.0, update the npm module to that `npm install --save sonos@0.9` and you should have the addSpotify method available to you :)

**Comment by ryanjohnstone** [comment]
Awesome, thanks
